### ISSUE TITLE
All daily-iso tests failing with "org.fedoraproject.Anaconda.Modules.Payloads:RuntimeError: The transaction process has ended abruptly: DNF done"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1009]
Since: 2023-09-21
```
01:01:00,021 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-InstallPackagesTask-1 (139836237428416)
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-InstallPackagesTask-1 has failed: Traceback (most recent call last):
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/threading.py", line 989, in run
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/dnf/installation.py", line 248, in run
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._dnf_manager.install_packages(self.report_progress)
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/dnf/dnf_manager.py", line 683, in install_packages
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    process_transaction_progress(queue, callback)
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/dnf/transaction_progress.py", line 57, in process_transaction_progress
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise RuntimeError("The transaction process has ended abruptly: " + msg)
01:01:00,117 WARNING org.fedoraproject.Anaconda.Modules.Payloads:RuntimeError: The transaction process has ended abruptly: DNF done
01:01:00,118 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-InstallPackagesTask-1 (139836237428416)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    result = self._handle_call(
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:             ^^^^^^^^^^^^^^^^^^
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return handler(*parameters, **additional_args)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self.implementation.finish()
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 173, in finish
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    thread_manager.raise_if_error(self._thread_name)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 171, in raise_if_error
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise exc_info[1]
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/threading.py", line 989, in run
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/dnf/installation.py", line 248, in run
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._dnf_manager.install_packages(self.report_progress)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/dnf/dnf_manager.py", line 683, in install_packages
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    process_transaction_progress(queue, callback)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/dnf/transaction_progress.py", line 57, in process_transaction_progress
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise RuntimeError("The transaction process has ended abruptly: " + msg)
01:01:00,174 WARNING org.fedoraproject.Anaconda.Modules.Payloads:RuntimeError: The transaction process has ended abruptly: DNF done
01:01:00,208 INFO anaconda:anaconda: core.threads: Thread Failed: AnaTaskThread-RunInstallationTask-1 (140186871658176)
```
 
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/12681680/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/12681682/virt-install.log)

installation image packages diff:
[pkg_diff.txt](https://github.com/rhinstaller/kickstart-tests/files/12681683/pkg_diff.txt)

**Comment by rvykydal** [comment]
Anaconda BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2242076,
seems to be caused by https://bugzilla.redhat.com/show_bug.cgi?id=1908253
