### ISSUE TITLE
60 daily-iso tests failing with "org.fedoraproject.Anaconda.Modules.Storage:AttributeError: 'SwapSpace' object has no attribute 'fstab'"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1021]
Since 2023_11_02
```
01:06:27,351 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:blivet:executing action: [187] create device lvmlv vg01-swap_lv (id 182)
01:06:27,351 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-CreateStorageLayoutTask-1 (139923372943040)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-CreateStorageLayoutTask-1 has failed: Traceback (most recent call last):
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/threading.py", line 989, in run
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 83, in run
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._turn_on_filesystems(
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 163, in _turn_on_filesystems
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.do_it(callbacks)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 53, in run_with_lock
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/blivet.py", line 122, in do_it
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.devicetree.actions.process(callbacks=callbacks, devices=self.devices, fstab=self.fstab)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/actionlist.py", line 47, in wrapped_func
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return func(obj, *args, **kwargs)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/actionlist.py", line 293, in process
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    entry = fstab.entry_from_device(action.device)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/fstab.py", line 391, in entry_from_device
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    entry.spec = self._get_spec(device)
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:                 ^^^^^^^^^^^^^^^^^^^^^^
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/fstab.py", line 699, in _get_spec
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:    spec_type = device.format.fstab.spec_type or self.spec_type
01:06:27,353 WARNING org.fedoraproject.Anaconda.Modules.Storage:                ^^^^^^^^^^^^^^^^^^^
01:06:27,354 WARNING org.fedoraproject.Anaconda.Modules.Storage:AttributeError: 'SwapSpace' object has no attribute 'fstab'
01:06:27,355 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-CreateStorageLayoutTask-1 (139923372943040)
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:             ^^^^^^^^^^^^^^^^^^
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters, **additional_args)
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.finish()
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 173, in finish
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    thread_manager.raise_if_error(self._thread_name)
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 171, in raise_if_error
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise exc_info[1]
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/threading.py", line 989, in run
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 83, in run
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._turn_on_filesystems(
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 163, in _turn_on_filesystems
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.do_it(callbacks)
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 53, in run_with_lock
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
01:06:27,366 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/blivet.py", line 122, in do_it
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.devicetree.actions.process(callbacks=callbacks, devices=self.devices, fstab=self.fstab)
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/actionlist.py", line 47, in wrapped_func
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return func(obj, *args, **kwargs)
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/actionlist.py", line 293, in process
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:    entry = fstab.entry_from_device(action.device)
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/fstab.py", line 391, in entry_from_device
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:    entry.spec = self._get_spec(device)
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:                 ^^^^^^^^^^^^^^^^^^^^^^
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/fstab.py", line 699, in _get_spec
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:    spec_type = device.format.fstab.spec_type or self.spec_type
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:                ^^^^^^^^^^^^^^^^^^^
01:06:27,367 WARNING org.fedoraproject.Anaconda.Modules.Storage:AttributeError: 'SwapSpace' object has no attribute 'fstab'
01:06:27,369 INFO anaconda:anaconda: core.threads: Thread Failed: AnaTaskThread-RunInstallationTask-1 (140055748273856)
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/13235807/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/13235810/virt-install.log)

**Comment by rvykydal** [comment]
Packages diff:
```
< amd-gpu-firmware-20230919-1.fc40.noarch
---
> amd-gpu-firmware-20231030-1.fc40.noarch
> amd-ucode-firmware-20231030-1.fc40.noarch
23c24
< atheros-firmware-20230919-1.fc40.noarch
---
> atheros-firmware-20231030-1.fc40.noarch
41c42
< blivet-data-3.8.2-1.20231027120105874149.3.9.devel.5.gee7cbae5.fc40.noarch
---
> blivet-data-3.8.2-1.20231101140644276287.3.9.devel.13.g9f87d4bc.fc40.noarch
45c46
< brcmfmac-firmware-20230919-1.fc40.noarch
---
> brcmfmac-firmware-20231030-1.fc40.noarch
69,70c70,71
< createrepo_c-1.0.2-20231031004752.0.ge876363.fc40.x86_64
< createrepo_c-libs-1.0.2-20231031004752.0.ge876363.fc40.x86_64
---
> createrepo_c-1.0.2-20231101005053.1.g59f31fc.fc40.x86_64
> createrepo_c-libs-1.0.2-20231101005053.1.g59f31fc.fc40.x86_64
99,100c100,101
< dnf-4.18.0-20231031004755.3.g3c8c66f1.fc40.noarch
< dnf-data-4.18.0-20231031004755.3.g3c8c66f1.fc40.noarch
---
> dnf-4.18.0-20231101005055.3.g3c8c66f1.fc40.noarch
> dnf-data-4.18.0-20231101005055.3.g3c8c66f1.fc40.noarch
107c108
< drpm-0.5.2-20231031004747.0.g48c0fde.fc40.x86_64
---
> drpm-0.5.2-20231101005050.0.g48c0fde.fc40.x86_64
110c111
< dvb-firmware-20230919-1.fc40.noarch
---
> dvb-firmware-20231030-1.fc40.noarch
241c242
< intel-gpu-firmware-20230919-1.fc40.noarch
---
> intel-gpu-firmware-20231030-1.fc40.noarch
251,253c252,254
< iwlegacy-firmware-20230919-1.fc40.noarch
< iwlwifi-dvm-firmware-20230919-1.fc40.noarch
< iwlwifi-mvm-firmware-20230919-1.fc40.noarch
---
> iwlegacy-firmware-20231030-1.fc40.noarch
> iwlwifi-dvm-firmware-20231030-1.fc40.noarch
> iwlwifi-mvm-firmware-20231030-1.fc40.noarch
268,272c269,273
< kernel-6.6.0-61.fc40.x86_64
< kernel-core-6.6.0-61.fc40.x86_64
< kernel-modules-6.6.0-61.fc40.x86_64
< kernel-modules-core-6.6.0-61.fc40.x86_64
< kernel-modules-extra-6.6.0-61.fc40.x86_64
---
> kernel-6.7.0-0.rc0.20231031git5a6a09e97199.2.fc40.x86_64
> kernel-core-6.7.0-0.rc0.20231031git5a6a09e97199.2.fc40.x86_64
> kernel-modules-6.7.0-0.rc0.20231031git5a6a09e97199.2.fc40.x86_64
> kernel-modules-core-6.7.0-0.rc0.20231031git5a6a09e97199.2.fc40.x86_64
> kernel-modules-extra-6.7.0-0.rc0.20231031git5a6a09e97199.2.fc40.x86_64
351c352
< libcomps-0.1.20-20231031004748.3.g220078b.fc40.x86_64
---
> libcomps-0.1.20-20231101005051.3.g220078b.fc40.x86_64
359c360
< libdnf-0.72.0-20231031004753.1.gea275a0f.fc40.x86_64
---
> libdnf-0.72.0-20231101005054.1.gea275a0f.fc40.x86_64
365c366
< libertas-firmware-20230919-1.fc40.noarch
---
> libertas-firmware-20231030-1.fc40.noarch
388c389
< libhandy-1.8.2-3.fc40.x86_64
---
> libhandy-1.8.2-4.fc40.x86_64
406c407
< libmodulemd-2.15.0-20231031004746.0.gbfde7f2.fc40.x86_64
---
> libmodulemd-2.15.0-20231101005049.0.gbfde7f2.fc40.x86_64
412,413c413,414
< libnl3-3.8.0-1.fc40.x86_64
< libnl3-cli-3.8.0-1.fc40.x86_64
---
> libnl3-3.8.0-2.fc40.x86_64
> libnl3-cli-3.8.0-2.fc40.x86_64
427c428
< librepo-1.17.0-20231031004747.0.gae727d9.fc40.x86_64
---
> librepo-1.17.0-20231101005050.0.gae727d9.fc40.x86_64
447c448
< libsolv-0.7.25-20231031004742.0.gf1be8bf3.fc40.x86_64
---
> libsolv-0.7.25-20231101005046.0.gf1be8bf3.fc40.x86_64
498,499c499,500
< linux-firmware-20230919-1.fc40.noarch
< linux-firmware-whence-20230919-1.fc40.noarch
---
> linux-firmware-20231030-1.fc40.noarch
> linux-firmware-whence-20231030-1.fc40.noarch
535c536
< mt7xxx-firmware-20230919-1.fc40.noarch
---
> mt7xxx-firmware-20231030-1.fc40.noarch
539,540c540,541
< mutter-45.0-15.fc40.x86_64
< mutter-common-45.0-15.fc40.noarch
---
> mutter-45.1-1.fc40.x86_64
> mutter-common-45.1-1.fc40.noarch
563c564
< nvidia-gpu-firmware-20230919-1.fc40.noarch
---
> nvidia-gpu-firmware-20231030-1.fc40.noarch
579,580c580,581
< p11-kit-0.25.1-1.fc40.x86_64
< p11-kit-trust-0.25.1-1.fc40.x86_64
---
> p11-kit-0.25.2-1.fc40.x86_64
> p11-kit-trust-0.25.2-1.fc40.x86_64
599,600c600,601
< policycoreutils-3.5-7.fc39.x86_64
< policycoreutils-python-utils-3.5-7.fc39.noarch
---
> policycoreutils-3.5-8.fc40.x86_64
> policycoreutils-python-utils-3.5-8.fc40.noarch
614c615
< python3-blivet-3.8.2-1.20231027120105874149.3.9.devel.5.gee7cbae5.fc40.noarch
---
> python3-blivet-3.8.2-1.20231101140644276287.3.9.devel.13.g9f87d4bc.fc40.noarch
622c623
< python3-dnf-4.18.0-20231031004755.3.g3c8c66f1.fc40.noarch
---
> python3-dnf-4.18.0-20231101005055.3.g3c8c66f1.fc40.noarch
626c627
< python3-hawkey-0.72.0-20231031004753.1.gea275a0f.fc40.x86_64
---
> python3-hawkey-0.72.0-20231101005054.1.gea275a0f.fc40.x86_64
630,631c631,633
< python3-libcomps-0.1.20-20231031004748.3.g220078b.fc40.x86_64
< python3-libdnf-0.72.0-20231031004753.1.gea275a0f.fc40.x86_64
---
> python3-libcomps-0.1.20-20231101005051.3.g220078b.fc40.x86_64
> python3-libdnf-0.72.0-20231101005054.1.gea275a0f.fc40.x86_64
> python3-libmount-2.39.2-1.fc40.x86_64
639c641
< python3-policycoreutils-3.5-7.fc39.noarch
---
> python3-policycoreutils-3.5-8.fc40.noarch
662c664
< realtek-firmware-20230919-1.fc40.noarch
---
> realtek-firmware-20231030-1.fc40.noarch
702c704
< strace-6.5-1.fc40.x86_64
---
```
[packages_diff.txt](https://github.com/rhinstaller/kickstart-tests/files/13235828/packages_diff.txt)

**Comment by rvykydal** [comment]
@vojtechtrefny Hi Vojto, do you have any hint?

**Comment by vojtechtrefny** [comment]
We merged fstab support to blivet yesterday (https://github.com/storaged-project/blivet/pull/1119), this is caused by it, @japokorn we need to fix this asap.

**Comment by rvykydal** [comment]
> I have created a PR [#1166](https://github.com/storaged-project/blivet/pull/1166) that should fix the issue, but it is still missing tests and some other stuff. Should be okay as a temporary fix if needed, though.

I think we can wait a few days. Currently it is affecting only the daily kstests afaik.

**Comment by japokorn** [comment]
blivet [#1166](https://github.com/storaged-project/blivet/pull/1166) is now complete and has been merged. It should fix the problem.
