### ISSUE TITLE
All daily-iso tests failing with: "org.fedoraproject.Anaconda.Modules.Storage:TypeError: cannot pickle 'FSExt2Info' object"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1025]
Since 11-11-2023

```
23:31:51,974 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-ScanDevicesTask-1 (139847364974272)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-ScanDevicesTask-1 has failed: Traceback (most recent call last):
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/threading.py", line 989, in run 
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/reset.py", line 63, in run
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._reset_storage(self._storage)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/reset.py", line 82, in _reset_storage
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.reset()
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 53, in run_with_lock
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs) 
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/devicetree/model.py", line 261, in reset
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    super().reset(cleanup_only=cleanup_only)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 53, in run_with_lock
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/blivet.py", line 149, in reset
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.devicetree.populate(cleanup_only=cleanup_only)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 53, in run_with_lock
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/populator/populator.py", line 446, in populate
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._populate()
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 53, in run_with_lock
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/populator/populator.py", line 490, in _populate
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.handle_device(dev)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 53, in run_with_lock
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/populator/populator.py", line 311, in handle_device
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    device.original_format = copy.deepcopy(device.format)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/copy.py", line 162, in deepcopy
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    y = _reconstruct(x, memo, *rv)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:        ^^^^^^^^^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/copy.py", line 259, in _reconstruct
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    state = deepcopy(state, memo)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:            ^^^^^^^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/copy.py", line 136, in deepcopy
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    y = copier(x, memo)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:        ^^^^^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/copy.py", line 221, in _deepcopy_dict
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    y[deepcopy(key, memo)] = deepcopy(value, memo)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:                             ^^^^^^^^^^^^^^^^^^^^^ 
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/copy.py", line 151, in deepcopy
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:    rv = reductor(4)
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:         ^^^^^^^^^^^
23:31:51,978 WARNING org.fedoraproject.Anaconda.Modules.Storage:TypeError: cannot pickle 'FSExt2Info' object
23:31:51,980 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-ScanDevicesTask-1 (139847364974272)
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/13333400/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/13333402/virt-install.log)

**Comment by rvykydal** [comment]
@vojtechtrefny Hi Vojta, does it ring any bells?

**Comment by vojtechtrefny** [comment]
Yes, we started using libblockdev filesystem plugin for filesystem information. I definitely didn't expect `deepcopy` to cause some problems. Working on a fix right now.

**Comment by rvykydal** [comment]
@vojtechtrefny fixed in the last daily run, thank you!
