### ISSUE TITLE
daily-iso flake: "pyanaconda.modules.common.errors.general.UnavailableValueError: The kernel version list is not available."

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1035]
since 11-28-2023
```
00:00:05,961 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-CleanUpDownloadLocationTask-1 (140455246190272)
00:00:05,964 INFO anaconda:anaconda: installation: Queue started: Bootloader installation (7/16)
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.Payloads.GetKernelVersionList has failed with an exception:
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    result = self._handle_call(
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:             ^^^^^^^^^^^^^^^^^^
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return handler(*parameters, **additional_args)
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payloads_interface.py", line 121, in GetKernelVersionList
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return self.implementation.get_kernel_version_list()
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payloads.py", line 158, in get_kernel_version_list
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    kernel_version_list += self.active_payload.get_kernel_version_list()
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/payload_base.py", line 168, in get_kernel_version_list
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise UnavailableValueError("The kernel version list is not available.")
00:00:06,034 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.general.UnavailableValueError: The kernel version list is not available.
00:00:06,035 WARNING org.fedoraproject.Anaconda.Modules.Payloads:DEBUG:anaconda.modules.payloads.payload.payload_base:The kernel version list is set to: ['6.7.0-0.rc2.20231125git0f5cc96c367f.26.fc40.x86_64']
00:00:06,039 INFO anaconda:anaconda: core.threads: Thread Failed: AnaTaskThread-RunInstallationTask-1 (140527916799680)
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/13544539/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/13544540/virt-install.log)

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/13544543/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/13544544/virt-install.log)

**Comment by aiace9** [comment]
I have the same problem, or at least the problem I am facing shows the same symptoms. It shows up in both fedora 39 and 40. 

I just finished debugging it, and it is 100% due to Infiniband and IPoIB. I see that rdma-core also appears in your log, so I guess you have similar hardware. For now, the workaround I found to pinpoint the issue was to disable the card from ipmi. Tomorrow I will try to blacklist ipoib or mlx5_core and see how it goes. 

By the way, I looked a little in Anaconda, and I guess that the problem is not strictly Anaconda itself but is linked to Dbus and the publication of a payload interface.

**Comment by aiace9** [comment]
So if you don't need IB at installation time, blacklisting:
- mlx5_core
- mlx5_ib
- ib_ipoib
works.
