### ISSUE TITLE
rpm-ostree-containers-rhel9 failing on rhel9 with "org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.storage.UnknownDeviceError"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1050]
Started to fail 02-04-2024

```
00:23:02,882 INFO anaconda:anaconda: progress: Performing post-installation setup tasks
00:23:02,882 INFO anaconda:anaconda: installation: Queue started: Post-installation setup tasks (9/18)
00:23:02,882 INFO anaconda:anaconda: installation: Task started: Run post-installation setup tasks (13/44)
00:23:02,895 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:             DeviceTree.get_device_by_name: name:  ; incomplete: True ; hidden: True ;
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:             DeviceTree.get_device_by_name returned None
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.Storage.DeviceTree.Viewer.GetDeviceData has failed with an exception:
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 418, in _method_callback
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 234, in _handle_call
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters)
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/devicetree/viewer_interface.py", line 71, in GetDeviceData
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return DeviceData.to_structure(self.implementation.get_device_data(name))
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/devicetree/viewer.py", line 94, in get_device_data
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:    device = self._get_device(name)
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/devicetree/viewer.py", line 234, in _get_device
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise UnknownDeviceError(name)
00:23:02,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.storage.UnknownDeviceError
00:23:02,897 INFO anaconda:anaconda: threading: Thread Failed: AnaInstallThread (140677155386944)
00:23:02,898 DEBUG anaconda:anaconda: exception: running handleException
00:23:02,926 CRIT anaconda:anaconda: exception: Traceback (most recent call last):#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/threading.py", line 275, in run#012    threading.Thread.run(self)#012#012  File "/usr/lib64/python3.9/threading.py", line 917, in run#012    self._target(*self._args, **self._kwargs)#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation.py", line 399, in run_installation#012    queue.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 496, in start#012    self.run_task()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 458, in run_task#012    self._task(*self._task_args, **self._task_kwargs)#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/payload/rpmostreepayload.py", line 216, in post_install#012    task.run()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 423, in run#012    self._install_bootupd()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 431, in _install_bootupd#012    dev_data = DeviceData.from_structure(device_tree.GetDeviceData(bootloader.Drive))#012#012  File "/usr/lib/python3.9/site-packages/dasbus/client/handler.py", line 444, in _call_method#012    return self._get_method_reply(#012#012  File "/usr/lib/python3.9/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply#012    return self._handle_method_error(error)#012#012  File "/usr/lib/python3.9/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error#012    raise exception from None#012#012pyanaconda.modules.common.errors.storage.UnknownDeviceError
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14164229/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14164230/virt-install.log)

**Comment by rvykydal** [comment]
Packages diff:
```
355c355
< cups-libs-2.3.3op2-23.el9.x86_64
---
> cups-libs-2.3.3op2-22.el9.x86_64
396c396
< libnfsidmap-2.5.4-22.el9.x86_64
---
> libnfsidmap-2.5.4-21.el9.x86_64
653,654c653,654
< kernel-modules-core-5.14.0-417.el9.x86_64
< kernel-core-5.14.0-417.el9.x86_64
---
> kernel-modules-core-5.14.0-416.el9.x86_64
> kernel-core-5.14.0-416.el9.x86_64
657c657
< kernel-modules-5.14.0-417.el9.x86_64
---
> kernel-modules-5.14.0-416.el9.x86_64
691,692c691,692
< anaconda-tui-34.25.4.5-1.el9.x86_64
< anaconda-core-34.25.4.5-1.el9.x86_64
---
> anaconda-tui-34.25.4.4-1.el9.x86_64
> anaconda-core-34.25.4.4-1.el9.x86_64
715c715
< anaconda-widgets-34.25.4.5-1.el9.x86_64
---
> anaconda-widgets-34.25.4.4-1.el9.x86_64
725,726c725,726
< anaconda-gui-34.25.4.5-1.el9.x86_64
< anaconda-34.25.4.5-1.el9.x86_64
---
> anaconda-gui-34.25.4.4-1.el9.x86_64
> anaconda-34.25.4.4-1.el9.x86_64
733c733
< anaconda-install-img-deps-34.25.4.5-1.el9.x86_64
---
> anaconda-install-img-deps-34.25.4.4-1.el9.x86_64
737,739c737,739
< anaconda-dracut-34.25.4.5-1.el9.x86_64
< kernel-5.14.0-417.el9.x86_64
< kernel-modules-extra-5.14.0-417.el9.x86_64
---
> anaconda-dracut-34.25.4.4-1.el9.x86_64
> kernel-5.14.0-416.el9.x86_64
> kernel-modules-extra-5.14.0-416.el9.x86_64
741c741
< nfs-utils-2.5.4-22.el9.x86_64
---
> nfs-utils-2.5.4-21.el9.x86_64
```

Seems to be the `anaconda-install-img-deps-34.25.4.5-1.el9.x86_64` update, https://github.com/rhinstaller/anaconda/pull/5424.

Also see https://github.com/rhinstaller/kickstart-tests/pull/1037

**Comment by rvykydal** [comment]
The PR with fix: https://github.com/rhinstaller/kickstart-tests/pull/1052
Anyway, this test will probably be replaced by a better one, the https://github.com/rhinstaller/kickstart-tests/pull/1037 testing also system boot.

**Comment by rvykydal** [comment]
Fixed
