### ISSUE TITLE
rpm-ostree-container failing on daily-iso with "The command 'mount --bind /mnt/sysimage/home /mnt/sysroot/home' exited with the code 32."

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1053]
since 2024-02-07
```
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-PrepareOSTreeMountTargetsTask-1 has failed: Traceback (most recent call last):
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/threading.py", line 1010, in run
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback() 
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 287, in run
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._handle_other_mount_points(mount_points)
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 268, in _handle_other_mount_points
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._setup_internal_bindmount(mount, recurse=False)
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 178, in _setup_internal_bindmount
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    safe_exec_with_redirect("mount", [bindopt, src, dest])
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 54, in safe_exec_with_redirect
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError(
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: The command 'mount --bind /mnt/sysimage/home /mnt/sysroot/home' exited with the code 32.
00:18:14,158 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-PrepareOSTreeMountTargetsTask-1 (140663976888000)
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    result = self._handle_call(
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:             ^^^^^^^^^^^^^^^^^^
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return handler(*parameters, **additional_args)
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self.implementation.finish()
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 173, in finish
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    thread_manager.raise_if_error(self._thread_name)
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 171, in raise_if_error
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise exc_info[1]
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/threading.py", line 1010, in run
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run()) 
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 287, in run
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._handle_other_mount_points(mount_points)
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 268, in _handle_other_mount_points
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._setup_internal_bindmount(mount, recurse=False)
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 178, in _setup_internal_bindmount
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    safe_exec_with_redirect("mount", [bindopt, src, dest])
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 54, in safe_exec_with_redirect
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError( 
00:18:14,240 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: The command 'mount --bind /mnt/sysimage/home /mnt/sysroot/home' exited with the code 32.
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14192446/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14192449/virt-install.log)

**Comment by rvykydal** [comment]
Note - the test has been renamed to `rpm-ostree-container-silverblue`

**Comment by rvykydal** [comment]
Fixed
