### ISSUE TITLE
ui_vnc test failing on daily-iso: "pyanaconda.ui.gui.xkl_wrapper.XklWrapperError: Failed to initialize layouts"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1060]
Started to appear Feb 20 2024, but we have daily-iso nightlies missing for past 3 days.
(https://github.com/rhinstaller/kickstart-tests/actions/runs/7966154998/job/21746937010)
```
pyanaconda.ui.gui.xkl_wrapper.XklWrapperError: Failed to initialize layouts
2024-02-19 23:20:18,467 INFO: RESULT:ui_vnc:f5539215ba17:FAILED:Test failed on line: 23:20:07,835 CRIT anaconda:anaconda: exception: Traceback (most recent call last):

  File "/sbin/anaconda", line 585, in <module>
    anaconda.intf.run()

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/__init__.py", line 705, in run
    self._currentAction.refresh()

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/hubs/__init__.py", line 367, in refresh
    self._createBox()

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/hubs/__init__.py", line 143, in _createBox
    spoke = spokeClass(self.data, self.storage, self.payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/spokes/keyboard.py", line 320, in __init__
    self._xkl_wrapper = XklWrapper.get_instance()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/xkl_wrapper.py", line 84, in get_instance
    XklWrapper._instance = XklWrapper()
                           ^^^^^^^^^^^^

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/xkl_wrapper.py", line 118, in __init__
    raise XklWrapperError("Failed to initialize layouts")

pyanaconda.ui.gui.xkl_wrapper.XklWrapperError: Failed to initialize layouts
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14342563/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14342565/virt-install.log)

**Comment by rvykydal** [comment]
The last successful was 5 days ago (https://github.com/rhinstaller/kickstart-tests/actions/runs/7923574254) which is unfortunately the last daily result available for daily-iso (then for 3 days we failed to build the iso due to dnf copr repo issue).
Packages log:
[packages.diff.txt](https://github.com/rhinstaller/kickstart-tests/files/14345205/packages.diff.txt)
```
< adwaita-cursor-theme-46~alpha-2.fc40.noarch
< adwaita-icon-theme-46~alpha-2.fc40.noarch
---
> adwaita-cursor-theme-46~beta-1.fc41.noarch
> adwaita-icon-theme-46~beta-1.fc41.noarch
13,20c13,20
< anaconda-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
< anaconda-core-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
< anaconda-dracut-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
< anaconda-gui-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
< anaconda-install-env-deps-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
< anaconda-install-img-deps-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
< anaconda-tui-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
< anaconda-widgets-40.22-1.20240213045313127417.master.0.g0d74950c91.fc40.x86_64
---
> anaconda-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
> anaconda-core-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
> anaconda-dracut-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
> anaconda-gui-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
> anaconda-install-env-deps-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
> anaconda-install-img-deps-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
> anaconda-tui-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
> anaconda-widgets-41.1-1.20240219201358144167.master.7.gb3dfe6ad20.fc41.x86_64
22,24c22,24
< appstream-data-40-5.fc40.noarch
< at-spi2-atk-2.51.0-2.fc40.x86_64
< at-spi2-core-2.51.0-2.fc40.x86_64
---
> appstream-data-40-6.fc41.noarch
> at-spi2-atk-2.51.90-1.fc41.x86_64
> at-spi2-core-2.51.90-1.fc41.x86_64
26c26
< atk-2.51.0-2.fc40.x86_64
---
> atk-2.51.90-1.fc41.x86_64
40,42c40,42
< bind-libs-32:9.18.21-4.fc40.x86_64
< bind-license-32:9.18.21-4.fc40.noarch
< bind-utils-32:9.18.21-4.fc40.x86_64
---
> bind-libs-32:9.18.24-1.fc41.x86_64
> bind-license-32:9.18.24-1.fc41.noarch
> bind-utils-32:9.18.24-1.fc41.x86_64
45c45
< blivet-gui-runtime-2.5.0-99.20240206114408752910.main.1.g2f6da74.fc40.noarch
---
> blivet-gui-runtime-2.5.0-99.20240216111642406160.main.4.gbf71661.fc41.noarch
52c52
< btrfs-progs-6.7-1.fc40.x86_64
---
> btrfs-progs-6.7.1-1.fc41.x86_64
66a67,68
> composefs-1.0.3-1.fc40.x86_64
> composefs-libs-1.0.3-1.fc40.x86_64
73,74c75,76
< createrepo_c-1.0.4-20240213004749.0.g4ade5ea.fc40.x86_64
< createrepo_c-libs-1.0.4-20240213004749.0.g4ade5ea.fc40.x86_64
---
> createrepo_c-1.0.4-20240216004620.0.g4ade5ea.fc41.x86_64
> createrepo_c-libs-1.0.4-20240216004620.0.g4ade5ea.fc41.x86_64
80,81c82,83
< cups-libs-1:2.4.7-9.fc40.x86_64
< curl-8.6.0-4.fc40.x86_64
---
> cups-libs-1:2.4.7-11.fc41.x86_64
> curl-8.6.0-6.fc40.x86_64
156c158
< device-mapper-persistent-data-1.0.11-1.fc40.x86_64
---
> device-mapper-persistent-data-1.0.11-3.fc40.x86_64
159,160c161,162
< dnf-4.19.0-20240213004751.2.g259e4c9d.fc40.noarch
< dnf-data-4.19.0-20240213004751.2.g259e4c9d.fc40.noarch
---
> dnf-4.19.0-20240214004804.2.g259e4c9d.fc40.noarch
> dnf-data-4.19.0-20240214004804.2.g259e4c9d.fc40.noarch
162,167c164,169
< dracut-059-20.fc40.x86_64
< dracut-config-generic-059-20.fc40.x86_64
< dracut-live-059-20.fc40.x86_64
< dracut-network-059-20.fc40.x86_64
< dracut-squash-059-20.fc40.x86_64
< drpm-0.5.2-20240213004745.0.g48c0fde.fc40.x86_64
---
> dracut-059-22.fc40.x86_64
> dracut-config-generic-059-22.fc40.x86_64
> dracut-live-059-22.fc40.x86_64
> dracut-network-059-22.fc40.x86_64
> dracut-squash-059-22.fc40.x86_64
> drpm-0.5.2-20240219004826.0.g48c0fde.fc41.x86_64
181c183
< expat-2.5.0-5.fc40.x86_64
---
> expat-2.6.0-1.fc41.x86_64
185c187
< fedora-gpg-keys-40-0.2.noarch
---
> fedora-gpg-keys-41-0.1.noarch
187,193c189,195
< fedora-release-40-0.30.noarch
< fedora-release-common-40-0.30.noarch
< fedora-release-identity-basic-40-0.30.noarch
< fedora-repos-40-0.2.noarch
< fedora-repos-rawhide-40-0.2.noarch
< file-5.45-4.fc40.x86_64
< file-libs-5.45-4.fc40.x86_64
---
> fedora-release-41-0.1.noarch
> fedora-release-common-41-0.1.noarch
> fedora-release-identity-basic-41-0.1.noarch
> fedora-repos-41-0.1.noarch
> fedora-repos-rawhide-41-0.1.noarch
> file-5.45-5.fc41.x86_64
> file-libs-5.45-5.fc41.x86_64
216c218
< gdisk-1.0.9-8.fc40.x86_64
---
> gdisk-1.0.9-9.fc40.x86_64
222,224c224,226
< gettext-envsubst-0.22-4.fc40.x86_64
< gettext-libs-0.22-4.fc40.x86_64
< gettext-runtime-0.22-4.fc40.x86_64
---
> gettext-envsubst-0.22.4-1.fc40.x86_64
> gettext-libs-0.22.4-1.fc40.x86_64
> gettext-runtime-0.22.4-1.fc40.x86_64
226,229c228,231
< glibc-2.39-2.fc40.x86_64
< glibc-all-langpacks-2.39-2.fc40.x86_64
< glibc-common-2.39-2.fc40.x86_64
< glibc-gconv-extra-2.39-2.fc40.x86_64
---
> glibc-2.39.9000-1.fc41.x86_64
> glibc-all-langpacks-2.39.9000-1.fc41.x86_64
> glibc-common-2.39.9000-1.fc41.x86_64
> glibc-gconv-extra-2.39.9000-1.fc41.x86_64
231,233c233,235
< gnome-control-center-filesystem-46~alpha-1.fc40.noarch
< gnome-desktop3-44.0-11.fc40.x86_64
< gnome-desktop4-44.0-11.fc40.x86_64
---
> gnome-control-center-filesystem-46~beta.2-1.fc41.noarch
> gnome-desktop3-44.0-13.fc41.x86_64
> gnome-desktop4-44.0-13.fc41.x86_64
280c282
< gsettings-desktop-schemas-46~alpha-2.fc40.x86_64
---
> gsettings-desktop-schemas-46~beta-1.fc41.x86_64
289c291
< gtk4-4.13.6-2.fc40.x86_64
---
> gtk4-4.13.7-1.fc40.x86_64
310c312
< ipmitool-1.8.19-6.fc40.x86_64
---
> ipmitool-1.8.19-7.fc40.x86_64
317c319
< isomd5sum-1:1.2.3-23.fc40.x86_64
---
> isomd5sum-1:1.2.4-1.fc41.x86_64
334,338c336,340
< kernel-6.8.0-0.rc3.20240209git1f719a2f3fa6.31.fc40.x86_64
< kernel-core-6.8.0-0.rc3.20240209git1f719a2f3fa6.31.fc40.x86_64
< kernel-modules-6.8.0-0.rc3.20240209git1f719a2f3fa6.31.fc40.x86_64
< kernel-modules-core-6.8.0-0.rc3.20240209git1f719a2f3fa6.31.fc40.x86_64
< kernel-modules-extra-6.8.0-0.rc3.20240209git1f719a2f3fa6.31.fc40.x86_64
---
> kernel-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-core-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-modules-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-modules-core-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-modules-extra-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
386c388
< libblkid-2.40-0.8.rc1.fc40.x86_64
---
> libblkid-2.40-0.9.rc1.fc41.x86_64
414c416
< libcomps-0.1.20-20240213004746.5.ga71bce7.fc40.x86_64
---
> libcomps-0.1.20-20240219004827.5.ga71bce7.fc41.x86_64
416c418
< libcurl-minimal-8.6.0-4.fc40.x86_64
---
> libcurl-8.6.0-6.fc40.x86_64
419c421
< libdnf-0.73.0-20240213004750.0.g1f30b347.fc40.x86_64
---
> libdnf-0.73.0-20240219004830.0.g1f30b347.fc41.x86_64
422a425
> libei-1.2.1-1.fc40.x86_64
429c432
< libevent-2.1.12-11.fc40.x86_64
---
> libevent-2.1.12-12.fc40.x86_64
431c434
< libfdisk-2.40-0.8.rc1.fc40.x86_64
---
> libfdisk-2.40-0.9.rc1.fc41.x86_64
462,463c465,466
< libmodulemd-2.15.0-20240213004744.6.ga38019e.fc40.x86_64
< libmount-2.40-0.8.rc1.fc40.x86_64
---
> libmodulemd-2.15.0-20240219004825.6.ga38019e.fc41.x86_64
> libmount-2.40-0.9.rc1.fc41.x86_64
473c476
< libnvme-1.7.1-4.fc40.x86_64
---
> libnvme-1.8-1.fc41.x86_64
482,490c485,493
< librepo-1.17.0-20240211005131.0.gae727d9.fc40.x86_64
< libreport-2.17.11-6.fc40.x86_64
< libreport-anaconda-2.17.11-6.fc40.x86_64
< libreport-cli-2.17.11-6.fc40.x86_64
< libreport-filesystem-2.17.11-6.fc40.noarch
< libreport-gtk-2.17.11-6.fc40.x86_64
< libreport-plugin-bugzilla-2.17.11-6.fc40.x86_64
< libreport-plugin-reportuploader-2.17.11-6.fc40.x86_64
< libreport-web-2.17.11-6.fc40.x86_64
---
> librepo-1.17.0-20240219004826.0.gae727d9.fc41.x86_64
> libreport-2.17.14-1.fc40.x86_64
> libreport-anaconda-2.17.14-1.fc40.x86_64
> libreport-cli-2.17.14-1.fc40.x86_64
> libreport-filesystem-2.17.14-1.fc40.noarch
> libreport-gtk-2.17.14-1.fc40.x86_64
> libreport-plugin-bugzilla-2.17.14-1.fc40.x86_64
> libreport-plugin-reportuploader-2.17.14-1.fc40.x86_64
> libreport-web-2.17.14-1.fc40.x86_64
498c501
< libsmartcols-2.40-0.8.rc1.fc40.x86_64
---
> libsmartcols-2.40-0.9.rc1.fc41.x86_64
500c503
< libsolv-0.7.28-20240213004741.2.gf171207c.fc40.x86_64
---
> libsolv-0.7.28-20240219004823.13.g7b0788fb.fc41.x86_64
502a506,507
> libssh-0.10.6-4.fc40.x86_64
> libssh-config-0.10.6-4.fc40.noarch
504c509
< libstemmer-2.2.0-8.fc40.x86_64
---
> libstemmer-2.2.0-10.fc40.x86_64
514c519
< libudisks2-2.11.0-1.20240212162043620901.master.124.g8b15d24d.fc40.x86_64
---
> libudisks2-2.11.0-1.20240215131825717307.master.128.gc17f99e2.fc41.x86_64
519c524
< libuuid-2.40-0.8.rc1.fc40.x86_64
---
> libuuid-2.40-0.9.rc1.fc41.x86_64
532c537
< libwebp-1.3.2-4.fc40.x86_64
---
> libwebp-1.3.2-5.fc41.x86_64
548c553
< lm_sensors-libs-3.6.0-16.fc40.x86_64
---
> lm_sensors-libs-3.6.0-18.fc40.x86_64
577,578c582,583
< mutter-46~alpha-5.fc40.x86_64
< mutter-common-46~alpha-5.fc40.noarch
---
> mutter-46~beta-2.fc41.x86_64
> mutter-common-46~beta-2.fc41.noarch
591,597c596,602
< nspr-4.35.0-20.fc40.x86_64
< nss-3.97.0-1.fc40.x86_64
< nss-softokn-3.97.0-1.fc40.x86_64
< nss-softokn-freebl-3.97.0-1.fc40.x86_64
< nss-sysinit-3.97.0-1.fc40.x86_64
< nss-tools-3.97.0-1.fc40.x86_64
< nss-util-3.97.0-1.fc40.x86_64
---
> nspr-4.35.0-21.fc41.x86_64
> nss-3.98.0-1.fc41.x86_64
> nss-softokn-3.98.0-1.fc41.x86_64
> nss-softokn-freebl-3.98.0-1.fc41.x86_64
> nss-sysinit-3.98.0-1.fc41.x86_64
> nss-tools-3.98.0-1.fc41.x86_64
> nss-util-3.98.0-1.fc41.x86_64
602c607
< nvme-cli-2.7.1-4.fc40.x86_64
---
> nvme-cli-2.8-1.fc41.x86_64
614,615c619,620
< ostree-2024.2-1.fc40.x86_64
< ostree-libs-2024.2-1.fc40.x86_64
---
> ostree-2024.3-3.fc41.x86_64
> ostree-libs-2024.3-3.fc41.x86_64
619,620c624,625
< pam-1.6.0-1.fc40.x86_64
< pam-libs-1.6.0-1.fc40.x86_64
---
> pam-1.6.0-2.fc41.x86_64
> pam-libs-1.6.0-2.fc41.x86_64
659,663c664,668
< python3-dnf-4.19.0-20240213004751.2.g259e4c9d.fc40.noarch
< python3-gobject-3.46.0-3.fc40.x86_64
< python3-gobject-base-3.46.0-3.fc40.x86_64
< python3-gobject-base-noarch-3.46.0-3.fc40.noarch
< python3-hawkey-0.73.0-20240213004750.0.g1f30b347.fc40.x86_64
---
> python3-dnf-4.19.0-20240214004804.2.g259e4c9d.fc40.noarch
> python3-gobject-3.46.0-4.fc40.x86_64
> python3-gobject-base-3.46.0-4.fc40.x86_64
> python3-gobject-base-noarch-3.46.0-4.fc40.noarch
> python3-hawkey-0.73.0-20240219004830.0.g1f30b347.fc41.x86_64
668,671c673,676
< python3-libcomps-0.1.20-20240213004746.5.ga71bce7.fc40.x86_64
< python3-libdnf-0.73.0-20240213004750.0.g1f30b347.fc40.x86_64
< python3-libmount-2.40-0.8.rc1.fc40.x86_64
< python3-libreport-2.17.11-6.fc40.x86_64
---
> python3-libcomps-0.1.20-20240219004827.5.ga71bce7.fc41.x86_64
> python3-libdnf-0.73.0-20240219004830.0.g1f30b347.fc41.x86_64
> python3-libmount-2.40-0.9.rc1.fc41.x86_64
> python3-libreport-2.17.14-1.fc40.x86_64
690c695
< python3-satyr-0.42-5.fc40.x86_64
---
> python3-satyr-0.43-2.fc40.x86_64
692c697
< python3-setuptools-69.0.3-2.fc40.noarch
---
> python3-setuptools-69.0.3-3.fc41.noarch
718c723
< rsyslog-8.2310.0-4.fc40.x86_64
---
> rsyslog-8.2312.0-1.fc40.x86_64
721c726
< satyr-0.42-5.fc40.x86_64
---
> satyr-0.43-2.fc40.x86_64
723,724c728,729
< selinux-policy-40.12-1.fc40.noarch
< selinux-policy-targeted-40.12-1.fc40.noarch
---
> selinux-policy-40.13-1.fc40.noarch
> selinux-policy-targeted-40.13-1.fc40.noarch
728,729c733,734
< shadow-utils-2:4.14.0-5.fc40.x86_64
< shadow-utils-subid-2:4.14.0-5.fc40.x86_64
---
> shadow-utils-2:4.14.0-6.fc40.x86_64
> shadow-utils-subid-2:4.14.0-6.fc40.x86_64
758c763
< tmux-3.3a-8.20230918gitb202a2f.fc40.x86_64
---
> tmux-3.4-1.fc41.x86_64
761,763c766,768
< udisks2-2.11.0-1.20240212162043620901.master.124.g8b15d24d.fc40.x86_64
< udisks2-iscsi-2.11.0-1.20240212162043620901.master.124.g8b15d24d.fc40.x86_64
< unbound-libs-1.19.0-8.fc40.x86_64
---
> udisks2-2.11.0-1.20240215131825717307.master.128.gc17f99e2.fc41.x86_64
> udisks2-iscsi-2.11.0-1.20240215131825717307.master.128.gc17f99e2.fc41.x86_64
> unbound-libs-1.19.1-2.fc41.x86_64
767,768c772,773
< util-linux-2.40-0.8.rc1.fc40.x86_64
< util-linux-core-2.40-0.8.rc1.fc40.x86_64
---
> util-linux-2.40-0.9.rc1.fc41.x86_64
> util-linux-core-2.40-0.9.rc1.fc41.x86_64
771,772c776,777
< vim-data-2:9.1.083-1.fc40.noarch
< vim-minimal-2:9.1.083-1.fc40.x86_64
---
> vim-data-2:9.1.113-1.fc41.noarch
> vim-minimal-2:9.1.113-1.fc41.x86_64
776c781
< webrtc-audio-processing-0.3.1-12.fc40.x86_64
---
> webrtc-audio-processing0.3-0.3.1-12.fc40.x86_64
```

**Comment by rvykydal** [comment]
Appears also on `default-systemd-target-vnc`.
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14402641/virt-install.log)


For both tests sometimes (1/4? of cases the test passes)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14402643/virt-install.log)

**Comment by rvykydal** [comment]
@M4rtinK obtained more narrow diff:
[packages.diff.2.txt](https://github.com/rhinstaller/kickstart-tests/files/14536827/packages.diff.2.txt)
making Gnome 46 Alpha -> Beta a suspect?
```
< adwaita-cursor-theme-46~alpha-2.fc40.noarch
< adwaita-icon-theme-46~alpha-2.fc40.noarch
---
> adwaita-cursor-theme-46~beta-1.fc41.noarch
> adwaita-icon-theme-46~beta-1.fc41.noarch
13,20c13,20
< anaconda-40.21-2.fc40.x86_64
< anaconda-core-40.21-2.fc40.x86_64
< anaconda-dracut-40.21-2.fc40.x86_64
< anaconda-gui-40.21-2.fc40.x86_64
< anaconda-install-env-deps-40.21-2.fc40.x86_64
< anaconda-install-img-deps-40.21-2.fc40.x86_64
< anaconda-tui-40.21-2.fc40.x86_64
< anaconda-widgets-40.21-2.fc40.x86_64
---
> anaconda-41.1-1.fc41.x86_64
> anaconda-core-41.1-1.fc41.x86_64
> anaconda-dracut-41.1-1.fc41.x86_64
> anaconda-gui-41.1-1.fc41.x86_64
> anaconda-install-env-deps-41.1-1.fc41.x86_64
> anaconda-install-img-deps-41.1-1.fc41.x86_64
> anaconda-tui-41.1-1.fc41.x86_64
> anaconda-widgets-41.1-1.fc41.x86_64
23,24c23,24
< at-spi2-atk-2.51.0-2.fc40.x86_64
< at-spi2-core-2.51.0-2.fc40.x86_64
---
> at-spi2-atk-2.51.90-1.fc41.x86_64
> at-spi2-core-2.51.90-1.fc41.x86_64
26c26
< atk-2.51.0-2.fc40.x86_64
---
> atk-2.51.90-1.fc41.x86_64
40,42c40,42
< bind-libs-32:9.18.21-4.fc40.x86_64
< bind-license-32:9.18.21-4.fc40.noarch
< bind-utils-32:9.18.21-4.fc40.x86_64
---
> bind-libs-32:9.18.24-1.fc41.x86_64
> bind-license-32:9.18.24-1.fc41.noarch
> bind-utils-32:9.18.24-1.fc41.x86_64
66a67,68
> composefs-1.0.3-1.fc40.x86_64
> composefs-libs-1.0.3-1.fc40.x86_64
80c82
< cups-libs-1:2.4.7-9.fc40.x86_64
---
> cups-libs-1:2.4.7-11.fc41.x86_64
226,229c228,231
< glibc-2.39-2.fc40.x86_64
< glibc-all-langpacks-2.39-2.fc40.x86_64
< glibc-common-2.39-2.fc40.x86_64
< glibc-gconv-extra-2.39-2.fc40.x86_64
---
> glibc-2.39.9000-1.fc41.x86_64
> glibc-all-langpacks-2.39.9000-1.fc41.x86_64
> glibc-common-2.39.9000-1.fc41.x86_64
> glibc-gconv-extra-2.39.9000-1.fc41.x86_64
231,233c233,235
< gnome-control-center-filesystem-46~alpha-1.fc40.noarch
< gnome-desktop3-44.0-12.fc40.x86_64
< gnome-desktop4-44.0-12.fc40.x86_64
---
> gnome-control-center-filesystem-46~beta.2-1.fc41.noarch
> gnome-desktop3-44.0-13.fc41.x86_64
> gnome-desktop4-44.0-13.fc41.x86_64
280c282
< gsettings-desktop-schemas-46~alpha-2.fc40.x86_64
---
> gsettings-desktop-schemas-46~beta-1.fc41.x86_64
317c319
< isomd5sum-1:1.2.3-23.fc40.x86_64
---
> isomd5sum-1:1.2.4-1.fc41.x86_64
334,338c336,340
< kernel-6.8.0-0.rc4.20240215git8d3dea210042.38.fc41.x86_64
< kernel-core-6.8.0-0.rc4.20240215git8d3dea210042.38.fc41.x86_64
< kernel-modules-6.8.0-0.rc4.20240215git8d3dea210042.38.fc41.x86_64
< kernel-modules-core-6.8.0-0.rc4.20240215git8d3dea210042.38.fc41.x86_64
< kernel-modules-extra-6.8.0-0.rc4.20240215git8d3dea210042.38.fc41.x86_64
---
> kernel-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-core-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-modules-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-modules-core-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
> kernel-modules-extra-6.8.0-0.rc4.20240216git4f5e5092fdbf.39.fc41.x86_64
386c388
< libblkid-2.40-0.8.rc1.fc40.x86_64
---
> libblkid-2.40-0.9.rc1.fc41.x86_64
422a425
> libei-1.2.1-1.fc40.x86_64
431c434
< libfdisk-2.40-0.8.rc1.fc40.x86_64
---
> libfdisk-2.40-0.9.rc1.fc41.x86_64
463c466
< libmount-2.40-0.8.rc1.fc40.x86_64
---
> libmount-2.40-0.9.rc1.fc41.x86_64
498c501
< libsmartcols-2.40-0.8.rc1.fc40.x86_64
---
> libsmartcols-2.40-0.9.rc1.fc41.x86_64
521c524
< libuuid-2.40-0.8.rc1.fc40.x86_64
---
> libuuid-2.40-0.9.rc1.fc41.x86_64
579,580c582,583
< mutter-46~alpha-5.fc40.x86_64
< mutter-common-46~alpha-5.fc40.noarch
---
> mutter-46~beta-2.fc41.x86_64
> mutter-common-46~beta-2.fc41.noarch
616,617c619,620
< ostree-2024.3-1.fc41.x86_64
< ostree-libs-2024.3-1.fc41.x86_64
---
> ostree-2024.3-3.fc41.x86_64
> ostree-libs-2024.3-3.fc41.x86_64
672c675
< python3-libmount-2.40-0.8.rc1.fc40.x86_64
---
> python3-libmount-2.40-0.9.rc1.fc41.x86_64
694c697
< python3-setuptools-69.0.3-2.fc40.noarch
---
> python3-setuptools-69.0.3-3.fc41.noarch
769,770c772,773
< util-linux-2.40-0.8.rc1.fc40.x86_64
< util-linux-core-2.40-0.8.rc1.fc40.x86_64
---
> util-linux-2.40-0.9.rc1.fc41.x86_64
> util-linux-core-2.40-0.9.rc1.fc41.x86_64
773,774c776,777
< vim-data-2:9.1.083-1.fc40.noarch
< vim-minimal-2:9.1.083-1.fc40.x86_64
---
> vim-data-2:9.1.113-1.fc41.noarch
> vim-minimal-2:9.1.113-1.fc41.x86_64
```

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/1074
