### ISSUE TITLE
rpm-ostree-container failing on rhel10 with "PayloadInstallationError: The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=quay.io/centos-bootc/centos-bootc:stream10 --transport=registry --no-signature-verification' exited with the code 1."

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1107]
```
00:42:01,228 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Running Thread: AnaTaskThread-DeployOSTreeTask-1 (139805528688320)
00:42:01,229 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.modules.common.task.task:Deploy OSTree
00:42:01,231 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:Running... ostree admin --sysroot=/mnt/sysimage os-init default
00:42:01,265 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:ostree/deploy/default initialized as OSTree stateroot
00:42:01,266 WARNING org.fedoraproject.Anaconda.Modules.Payloads:DEBUG:program:Return code: 0
00:42:01,267 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.modules.payloads.payload.rpm_ostree.installation:ostree image deploy starting
00:42:01,267 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:Running... ostree container image deploy --sysroot=/mnt/sysimage --image=quay.io/centos-bootc/centos-bootc:stream10 --transport=registry --no-signature-verification
00:42:02,834 INFO kernel:SELinux:  Context system_u:object_r:container_var_lib_t:s0 is not valid (left unmapped).
00:42:02,878 INFO ostree-containe:Fetching ostree-unverified-registry:quay.io/centos-bootc/centos-bootc:stream10
00:42:02,896 NOTICE kernel:audit: type=1400 audit(1711327322.893:264): avc:  denied  { name_connect } for  pid=3117 comm="skopeo" dest=443 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=1
00:42:02,896 NOTICE audit:AVC avc:  denied  { name_connect } for  pid=3117 comm="skopeo" dest=443 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=1
00:42:03,179 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:error: Performing deployment: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: reading manifest stream10 in quay.io/centos-bootc/centos-bootc: manifest unknown
00:42:03,179 WARNING org.fedoraproject.Anaconda.Modules.Payloads:DEBUG:program:Return code: 1
00:42:03,179 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-DeployOSTreeTask-1 (139805528688320)
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-DeployOSTreeTask-1 has failed: Traceback (most recent call last):
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/threading.py", line 1010, in run
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 620, in run
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    safe_exec_with_redirect(
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 54, in safe_exec_with_redirect
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError(
00:42:03,183 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=quay.io/centos-bootc/centos-bootc:stream10 --transport=registry --no-signature-verification' exited with the code 1.
00:42:03,184 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-DeployOSTreeTask-1 (139805528688320)
00:42:03,266 WARNING brltty:unsupported generic resource identifier: bluetooth:
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    result = self._handle_call(
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:             ^^^^^^^^^^^^^^^^^^
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return handler(*parameters, **additional_args)
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self.implementation.finish()
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 173, in finish
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    thread_manager.raise_if_error(self._thread_name)
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 171, in raise_if_error
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise exc_info[1]
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/threading.py", line 1010, in run
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 620, in run
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    safe_exec_with_redirect(
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 54, in safe_exec_with_redirect
00:42:03,285 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError(
00:42:03,286 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=quay.io/centos-bootc/centos-bootc:stream10 --transport=registry --no-signature-verification' exited with t
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14741909/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14741912/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/1113
