### ISSUE TITLE
autopart-fstype failing on rhel10 with "pyanaconda.modules.common.errors.general.AnacondaError: new value ext2 is not valid as a default fs type"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1178]
Follow-up of https://github.com/rhinstaller/kickstart-tests/pull/1174

```
00:05:57,748 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:blivet:                                Ext2FS.supported: supported: False ;
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.ReadKickstart has failed with an exception:
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:             ^^^^^^^^^^^^^^^^^^
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters, **additional_args)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/dasbus/server/property.py", line 51, in wrapper
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = method(obj, *args, **kwargs)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/base/base_interface.py", line 91, in ReadKickstart
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.read_kickstart(kickstart)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/base/base.py", line 233, in read_kickstart
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.process_kickstart(handler)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/storage.py", line 151, in process_kickstart
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.storage.set_default_fstype(data.autopart.fstype)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 49, in run_with_lock
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/blivet.py", line 1197, in set_default_fstype
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._check_valid_fstype(newtype)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 49, in run_with_lock
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/blivet.py", line 1182, in _check_valid_fstype
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise ValueError("new value %s is not valid as a default fs type" % newtype)
00:05:57,750 WARNING org.fedoraproject.Anaconda.Modules.Storage:ValueError: new value ext2 is not valid as a default fs type
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Boss.ReadKickstartFile has failed with an exception:
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:Traceback (most recent call last):
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    result = self._handle_call(
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:             ^^^^^^^^^^^^^^^^^^
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    return handler(*parameters, **additional_args)
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/boss/boss_interface.py", line 74, in ReadKickstartFile
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    self.implementation.read_kickstart_file(path)
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/boss/boss.py", line 86, in read_kickstart_file
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    return self._kickstart_manager.read_kickstart_file(path)
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/boss/kickstart_manager/kickstart_manager.py", line 58, in read_kickstart_file
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    reports = self._distribute_to_modules(elements)
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/boss/kickstart_manager/kickstart_manager.py", line 111, in _distribute_to_modules
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    observer.proxy.ReadKickstart(module_kickstart)
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 450, in _call_method
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    return self._get_method_reply(
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:           ^^^^^^^^^^^^^^^^^^^^^^^
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    return self._handle_method_error(error)
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:    raise exception from None
00:05:57,754 WARNING org.fedoraproject.Anaconda.Boss:pyanaconda.modules.common.errors.general.AnacondaError: new value ext2 is not valid as a default fs type
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/15345618/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/15345619/virt-install.log)

**Comment by rvykydal** [comment]
Fails also on rhel 10: https://github.com/rhinstaller/kickstart-tests/actions/runs/9135337646

**Comment by jstodola** [comment]
FYI, we hit a possibly related ext2/ext3 issue: https://issues.redhat.com/browse/RHEL-37249

**Comment by rvykydal** [comment]
The https://github.com/rhinstaller/kickstart-tests/issues/1179 hits the same issue.

**Comment by rvykydal** [comment]
PR to disable the tests: https://github.com/rhinstaller/kickstart-tests/pull/1196

**Comment by rvykydal** [comment]
The issue was fixed
