### ISSUE TITLE
raid-ddf flake on rhel9 with "Cannot allocate memory"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1186]
05-16-2024
```
23:54:18,680 INFO anaconda:librepo: Downloading: http://download.eng.bos.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.5.0/compose/AppStream/x86_64/os/Packages/gawk-all-langpacks-5.1.0-6.el9.x86_64.rpm
23:54:18,683 INFO anaconda:librepo: Downloading: http://download.eng.bos.redhat.com/rhel-9/nightly/RHEL-9/latest-RHEL-9.5.0/compose/AppStream/x86_64/os/Packages/liburing-2.5-1.el9.x86_64.rpm
23:54:18,840 ERR rsyslogd:imjournal: open() failed for path: '/var/lib/rsyslog/imjournal.state.tmp': Operation not permitted [v8.2310.0-4.el9 try https://www.rsyslog.com/e/2433 ]
23:54:18,840 ERR rsyslogd:imjournal: open() failed for path: '/var/lib/rsyslog/imjournal.state.tmp': Operation not permitted [v8.2310.0-4.el9 try https://www.rsyslog.com/e/2433 ]
23:54:18,840 ERR rsyslogd:imjournal: open() failed for path: '/var/lib/rsyslog/imjournal.state.tmp': Operation not permitted [v8.2310.0-4.el9 try https://www.rsyslog.com/e/2433 ]
23:54:18,840 ERR rsyslogd:imjournal: open() failed for path: '/var/lib/rsyslog/imjournal.state.tmp': Operation not permitted [v8.2310.0-4.el9 try https://www.rsyslog.com/e/2433 ]
23:54:21,649 INFO systemd:systemd-localed.service: Deactivated successfully.
23:54:23,901 INFO anaconda:packaging: Downloading packages finished.
23:54:23,902 INFO anaconda:anaconda: progress: Preparing transaction from installation source
23:54:24,517 INFO anaconda:anaconda: threading: Thread Failed: AnaInstallThread (139678321718848)
23:54:24,519 DEBUG anaconda:anaconda: exception: running handleException
23:54:24,598 CRIT anaconda:anaconda: exception: Traceback (most recent call last):#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/threading.py", line 275, in run#012    threading.Thread.run(self)#012#012  File "/usr/lib64/python3.9/threading.py", line 917, in run#012    self._target(*self._args, **self._kwargs)#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation.py", line 399, in run_installation#012    queue.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 496, in start#012    self.run_task()#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/installation_tasks.py", line 458, in run_task#012    self._task(*self._task_args, **self._task_kwargs)#012#012  File "/usr/lib64/python3.9/site-packages/pyanaconda/payload/dnf/payload.py", line 886, in install#012    process.start()#012#012  File "/usr/lib64/python3.9/multiprocessing/process.py", line 121, in start#012    self._popen = self._Popen(self)#012#012  File "/usr/lib64/python3.9/multiprocessing/context.py", line 224, in _Popen#012    return _default_context.get_context().Process._Popen(process_obj)#012#012  File "/usr/lib64/python3.9/multiprocessing/context.py", line 277, in _Popen#012    return Popen(process_obj)#012#012  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 19, in __init__#012    self._launch(process_obj)#012#012  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 66, in _launch#012    self.pid = os.fork()#012#012OSError: [Errno 12] Cannot allocate memory
23:54:24,612 DEBUG anaconda:anaconda: exception: Gtk running, queuing exception handler to the main loop
23:54:24,615 INFO anaconda:anaconda: threading: Thread Done: AnaInstallThread (139678321718848)
```
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/15374388/virt-install.log)

**Comment by rvykydal** [comment]
See also https://github.com/rhinstaller/kickstart-tests/issues/1151

**Comment by rvykydal** [comment]
Not hit anymore.
