### ISSUE TITLE
rpm-ostree-container-{bootc,luks} failing with "Payloads:INFO:program:error: Performing deployment: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: reading manifest eln in quay.io/centos-bootc/fedora-bootc: unauthorized: access to the requested resource is not authorized"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1230]
2024-06-26
rpm-ostree-conainer-bootc
rpm-ostree-container-luks
```
01:28:15,946 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:Running... ostree container image deploy --sysroot=/mnt/sysimage --image=quay.io/centos-bootc/fedora-bootc:eln --stateroot=test-stateroot --no-signature-verification
01:28:16,030 WARNING brltty:unsupported generic resource identifier: bluetooth:
01:28:17,441 INFO ostree-containe:Fetching ostree-unverified-registry:quay.io/centos-bootc/fedora-bootc:eln
01:28:17,453 NOTICE kernel:audit: type=1400 audit(1719365297.452:290): avc:  denied  { name_connect } for  pid=3216 comm="skopeo" dest=443 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=1
01:28:17,453 NOTICE audit:AVC avc:  denied  { name_connect } for  pid=3216 comm="skopeo" dest=443 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=1
01:28:17,829 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:error: Performing deployment: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: reading manifest eln in quay.io/centos-bootc/fedora-bootc: unauthorized: access to the requested resource is not authorized
01:28:17,830 WARNING org.fedoraproject.Anaconda.Modules.Payloads:DEBUG:program:Return code: 1
01:28:17,830 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-DeployOSTreeTask-1 (140305131112128)
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-DeployOSTreeTask-1 has failed: Traceback (most recent call last):
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/core/threads.py", line 280, in run
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~^^^^^^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/threading.py", line 990, in run
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~~~~^^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ~~~~~~~~^^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 629, in run
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    safe_exec_with_redirect(
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~~~~^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        "ostree",
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        ^^^^^^^^^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        args
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        ^^^^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    )
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ^
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 54, in safe_exec_with_redirect
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError(
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        "The command '{}' exited with the code {}.".format(" ".join([cmd] + argv), rc)
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    )
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=quay.io/centos-bootc/fedora-bootc:eln --stateroot=test-stateroot --no-signature-verification' exited with the code 1.
01:28:17,840 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-DeployOSTreeTask-1 (140305131112128)
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 455, in _method_callback
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    result = self._handle_call(
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        interface_name,
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ...<2 lines>...
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        **additional_args
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    )
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 265, in _handle_call
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return handler(*parameters, **additional_args)
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self.implementation.finish()
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/task/task.py", line 173, in finish
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    thread_manager.raise_if_error(self._thread_name)
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/core/threads.py", line 171, in raise_if_error
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise exc_info[1]
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/core/threads.py", line 280, in run
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~^^^^^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/threading.py", line 990, in run
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~~~~^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ~~~~~~~~^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 629, in run
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    safe_exec_with_redirect(
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ~~~~~~~~~~~~~~~~~~~~~~~^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        "ostree",
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        ^^^^^^^^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        args
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        ^^^^
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    )
01:28:17,898 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    ^
01:28:17,899 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 54, in safe_exec_with_redirect
01:28:17,899 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError(
01:28:17,899 WARNING org.fedoraproject.Anaconda.Modules.Payloads:        "The command '{}' exited with the code {}.".format(" ".join([cmd] + argv), rc)
01:28:17,899 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    )
01:28:17,899 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=quay.io/centos-bootc/fedora-bootc:eln --stateroot=test-stateroot --no-signature-verification' exited with the code 1.
```
[virt-install.log](https://github.com/user-attachments/files/15985245/virt-install.log)
[virt-install.log](https://github.com/user-attachments/files/15985248/virt-install.log)

**Comment by rvykydal** [comment]
Installer image packages diff: 
[installer.packages.diff.txt](https://github.com/user-attachments/files/15985319/installer.packages.diff.txt)

**Comment by rvykydal** [comment]
PR to disable temporarily: https://github.com/rhinstaller/kickstart-tests/pull/1232
