### ISSUE TITLE
rhel10 flake with "The call org.fedoraproject.Anaconda.Modules.Localization.GetCompositorSelectedLayout has failed with an exception"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1235]
06/27/2024
```
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.Localization.GetCompositorSelectedLayout has failed with an exception:
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:Traceback (most recent call last):
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    result = self._handle_call(
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:             ^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return handler(*parameters, **additional_args)
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/localization_interface.py", line 251, in GetCompositorSelectedLayout
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self.implementation.get_compositor_selected_layout()
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/localization.py", line 338, in get_compositor_selected_layout
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self.compositor_keyboard_manager.get_compositor_selected_layout()
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/localization.py", line 327, in compositor_keyboard_manager
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._compositor_keyboard_manager = GkKeyboardManager()
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:                                        ^^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/gk_keyboard_manager.py", line 33, in __init__
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._proxy.PropertiesChanged.connect(self._on_properties_changed)
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/proxy.py", line 161, in __getattr__
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    member = self._get_member(self._get_interface(name), name)
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:                              ^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/proxy.py", line 211, in _get_interface
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._handler.specification.members
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:13,998 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 212, in specification
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._specification = self._get_specification()
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:                          ^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 332, in _get_specification
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:    xml = self._call_method(
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:          ^^^^^^^^^^^^^^^^^^
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 450, in _call_method
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self._get_method_reply(
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self._handle_method_error(error)
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:    raise exception from None
00:00:14,007 WARNING org.fedoraproject.Anaconda.Modules.Localization:dasbus.error.DBusError: The name is not activatable 
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.Localization.GetCompositorLayouts has failed with an exception:
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:Traceback (most recent call last):
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    result = self._handle_call(
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:             ^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return handler(*parameters, **additional_args)
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/localization_interface.py", line 279, in GetCompositorLayouts
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self.implementation.get_compositor_layouts()
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/localization.py", line 347, in get_compositor_layouts
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self.compositor_keyboard_manager.get_compositor_layouts()
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/localization.py", line 327, in compositor_keyboard_manager
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._compositor_keyboard_manager = GkKeyboardManager()
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:                                        ^^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/localization/gk_keyboard_manager.py", line 33, in __init__
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._proxy.PropertiesChanged.connect(self._on_properties_changed)
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/proxy.py", line 161, in __getattr__
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    member = self._get_member(self._get_interface(name), name)
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:                              ^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/proxy.py", line 211, in _get_interface
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._handler.specification.members
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 212, in specification
00:00:14,017 WARNING org.fedoraproject.Anaconda.Modules.Localization:    self._specification = self._get_specification()
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:                          ^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 332, in _get_specification
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:    xml = self._call_method(
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:          ^^^^^^^^^^^^^^^^^^
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 450, in _call_method
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self._get_method_reply(
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:    return self._handle_method_error(error)
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:    raise exception from None
00:00:14,018 WARNING org.fedoraproject.Anaconda.Modules.Localization:dasbus.error.DBusError: The name is not activatable
```
[virt-install.log](https://github.com/user-attachments/files/16101537/virt-install.log)
[virt-install.log](https://github.com/user-attachments/files/16101538/virt-install.log)
[virt-install.log](https://github.com/user-attachments/files/16101540/virt-install.log)

**Comment by rvykydal** [comment]
06-28-2024
[virt-install.log](https://github.com/user-attachments/files/16101555/virt-install.log)

**Comment by rvykydal** [comment]
Last week - 7 occurences

**Comment by rvykydal** [comment]
Classify script update: https://github.com/rhinstaller/kickstart-tests/pull/1242

**Comment by jkonecny12** [comment]
Why is this marked as a flake?

**Comment by rvykydal** [comment]
> Why is this marked as a flake?

Because there was not any investigation yet.

**Comment by M4rtinK** [comment]
So we did see that happen in the past:

**Comment by M4rtinK** [comment]
There are 3 possible solutions I can think off right now:

- maybe look at timing of this call on Anaconda side & delay it a bit/make sure everything is up + some waiting time ?
- fix at GNOME Kiosk side
- switch to localed DBus API which I think might be already available in the current RHEL 10 version of GNOME Kiosk

**Comment by rvykydal** [comment]
Thank you!
