### ISSUE TITLE
network-static failing on daily-iso with "org.fedoraproject.Anaconda.Modules.Runtime:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1240]
07-04-2024
```
23:26:12,456 WARNING org.fedoraproject.Anaconda.Modules.Security:DEBUG:dasbus.connection:Publishing an object at /org/fedoraproject/Anaconda/Modules/Security.
23:26:12,456 WARNING org.fedoraproject.Anaconda.Modules.Security:INFO:anaconda.core.dbus:Connecting to the Anaconda bus at unix:path=/tmp/dbus-LCbyGzRdhA,guid=902adff1b150ea0744c49c5d6685ddca.
23:26:12,577 WARNING org.fedoraproject.Anaconda.Modules.Runtime:Traceback (most recent call last):
23:26:12,592 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "<frozen runpy>", line 198, in _run_module_as_main
23:26:12,592 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "<frozen runpy>", line 88, in _run_code
23:26:12,592 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/runtime/__main__.py", line 25, in <module>
23:26:12,592 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    service.run()
23:26:12,592 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ~~~~~~~~~~~^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/base/base.py", line 90, in run
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    self.publish()
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ~~~~~~~~~~~~^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/runtime/runtime.py", line 71, in publish
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    self._modules.publish_modules()
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/common/submodule_manager.py", line 38, in publish_modules
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    module.publish()
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ~~~~~~~~~~~~~~^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib64/python3.13/site-packages/pyanaconda/modules/runtime/user_interface/ui.py", line 56, in publish
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    DBus.publish_object(USER_INTERFACE.object_path, UIInterface(self))
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib/python3.13/site-packages/dasbus/connection.py", line 290, in publish_object
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    object_handler.connect_object()
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 355, in connect_object
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    self._register_object()
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ~~~~~~~~~~~~~~~~~~~~~^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib/python3.13/site-packages/dasbus/server/handler.py", line 370, in _register_object
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    self._message_bus.connection,
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib/python3.13/site-packages/dasbus/connection.py", line 169, in connection
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    self._connection = self._get_connection()
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:                       ~~~~~~~~~~~~~~~~~~~~^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib64/python3.13/site-packages/pyanaconda/core/dbus.py", line 46, in _get_connection
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    return self._provider.get_addressed_bus_connection(bus_address)
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:  File "/usr/lib/python3.13/site-packages/dasbus/connection.py", line 76, in get_addressed_bus_connection
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    return Gio.DBusConnection.new_for_address_sync(
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:        bus_address,
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:        ^^^^^^^^^^^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ...<2 lines>...
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:        cancellable
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:        ^^^^^^^^^^^
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    )
23:26:12,593 WARNING org.fedoraproject.Anaconda.Modules.Runtime:    ^
23:26:12,595 WARNING org.fedoraproject.Anaconda.Modules.Runtime:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
23:26:13,253 WARNING org.fedoraproject.Anaconda.Modules.Services:DEBUG:dasbus.connection:Registering a service name org.fedoraproject.Anaconda.Modules.Services.
23:26:13,282 INFO systemd:Starting lvm2-lvmdbusd.service - LVM2 D-Bus service...
```
[kstest.log](https://github.com/user-attachments/files/16129715/kstest.log)
[virt-install.log](https://github.com/user-attachments/files/16129735/virt-install.log)

**Comment by rvykydal** [comment]
Tracked in https://github.com/rhinstaller/kickstart-tests/issues/1388 now
