### ISSUE TITLE
lvm-cache-1 fails on rhel10 with "Waiting for 'CacheLv' method of the '/com/redhat/lvmdbus1/CachePool/0' object to finish failed"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1257]
07-15-2024
```
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.storage.installation:Failed to create storage layout: Failed to attach the cache pool 'home_cache' to the data LV: Waiting for 'CacheLv' method of the '/com/redhat/lvmdbus1/CachePool/0' object to finish failed: Failed to get Complete property of the /com/redhat/lvmdbus1/Job/1 object: Timeout was reached
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/gi/overrides/BlockDev.py", line 1243, in wrapped
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ret = orig_obj(*args, **kwargs)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:          ^^^^^^^^^^^^^^^^^^^^^^^^^
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.repository.GLib.GError: g-io-error-quark: Failed to attach the cache pool 'home_cache' to the data LV: Waiting for 'CacheLv' method of the '/com/redhat/lvmdbus1/CachePool/0' object to finish failed: Failed to get Complete property of the /com/redhat/lvmdbus1/Job/1 object: Timeout was reached (24)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:During handling of the above exception, another exception occurred:
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/devices/lvm.py", line 2835, in _create
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    blockdev.lvm.cache_create_cached_lv(self.vg.name, self._name, self.size, self.cache.size, self.cache.md_size,
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/gi/overrides/BlockDev.py", line 1265, in wrapped
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise transform[1](msg)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.overrides.BlockDev.LVMError: Failed to attach the cache pool 'home_cache' to the data LV: Waiting for 'CacheLv' method of the '/com/redhat/lvmdbus1/CachePool/0' object to finish failed: Failed to get Complete property of the /com/redhat/lvmdbus1/Job/1 object: Timeout was reached
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:During handling of the above exception, another exception occurred:
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 83, in run
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._turn_on_filesystems(
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 163, in _turn_on_filesystems
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.do_it(callbacks)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 49, in run_with_lock
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/blivet.py", line 127, in do_it
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.devicetree.actions.process(callbacks=callbacks, devices=self.devices, fstab=self.fstab)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/actionlist.py", line 46, in wrapped_func
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return func(obj, *args, **kwargs)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/actionlist.py", line 303, in process
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    action.execute(callbacks)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 49, in run_with_lock
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/deviceaction.py", line 330, in execute
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.device.create()
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 49, in run_with_lock
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/devices/storage.py", line 524, in create
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create()
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/threads.py", line 49, in run_with_lock
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/devices/lvm.py", line 2599, in decorated
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return meth(self, *args, **kwargs)  # pylint: disable=not-callable
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/blivet/devices/lvm.py", line 2838, in _create
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise errors.LVMError(err)
23:24:36,890 WARNING org.fedoraproject.Anaconda.Modules.Storage:blivet.errors.LVMError: Failed to attach the cache pool 'home_cache' to the data LV: Waiting for 'CacheLv' method of the '/com/redhat/lvmdbus1/CachePool/0' object to finish failed: Failed to get Complete property of the /com/redhat/lvmdbus1/Job/1 object: Timeout was reached
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-CreateStorageLayoutTask-1 (140667760150208)
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-CreateStorageLayoutTask-1 has failed: Traceback (most recent call last):
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/threading.py", line 1010, in run
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 95, in run
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageInstallationError(str(e)) from None
23:24:36,892 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.installation.StorageInstallationError: Failed to attach the cache pool 'home_cache' to the data LV: Waiting for 'CacheLv' method of the '/com/redhat/lvmdbus1/CachePool/0' object to finish failed: Failed to get Complete property of the /com/redhat/lvmdbus1/Job/1 object: Timeout was reached
23:24:36,896 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-CreateStorageLayoutTask-1 (140667760150208)
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 455, in _method_callback
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:             ^^^^^^^^^^^^^^^^^^
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.12/site-packages/dasbus/server/handler.py", line 265, in _handle_call
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters, **additional_args)
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.finish()
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 173, in finish
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    thread_manager.raise_if_error(self._thread_name)
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 171, in raise_if_error
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise exc_info[1]
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/threading.py", line 1010, in run
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/installation.py", line 95, in run
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageInstallationError(str(e)) from None
23:24:36,908 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.installation.StorageInstallationError: Failed to attach the cache pool 'home_cache' to the data LV: Waiting for 'CacheLv' method of the '/com/redhat/lvmdbus1/CachePool/0' object to finish failed: Failed to get Complete property of the /com/redhat/lvmdbus1/Job/1 object: Timeout was reached
23:24:40,559 WARNING brltty:unsupported generic resource identifier: bluetooth:
```
[virt-install.log](https://github.com/user-attachments/files/16284727/virt-install.log)

**Comment by rvykydal** [comment]
Closing, will be tracked in https://github.com/rhinstaller/kickstart-tests/issues/1311
