### ISSUE TITLE
some driverdisk and repo tests failing on github-kstest-30-f39-20240408 with "" 

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1342]
First hit 11-26-2024.
There are some kickstart tests failing on daily run of daily-iso: https://github.com/rhinstaller/kickstart-tests/actions/runs/12020594830

I suspect the update of the container to be the cause: https://github.com/rhinstaller/kickstart-tests/pull/1339
I didn't check totaly properly to confirm, but
- the test seem to fail in early stage during vm creating
- I run driverdisk-disk locally with the new daily-iso with the old container and it passed

The tests
```
driverdisk-disk
driverdisk-disk-kargs
packages-ignorebroken
proxy-auth
proxy-kickstart
repo-addrepo
repo-enable
repo-exclude
repo-include
```

The logs gathered by [weekly summary action](https://github.com/rhinstaller/kickstart-tests/actions/runs/12026144760) on the repo (see the 11-26-2024/logs-daily-iso/failed):
[weekly-logs-archive.zip](https://github.com/user-attachments/files/17931798/weekly-logs-archive.zip)

a snippet:

```
2024-11-26 00:22:38,222 DEBUG: Preparing test
2024-11-26 00:22:38,222 DEBUG: Linking image to temp directory /var/tmp/kstest-repo-addrepo.2024_11_26-00_22_38.layjd04a
2024-11-26 00:22:38,222 DEBUG: Running command: ['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-repo-addrepo.2024_11_26-00_22_38.layjd04a', '-t', '/opt/kstest/kickstart-tests/repo-addrepo.sh', 'prepare']
2024-11-26 00:22:38,390 DEBUG: stderr:
Traceback (most recent call last):
  File "/opt/kstest/kickstart-tests/scripts/generate-repository.py", line 55, in <module>
    import rpmfluff
  File "/usr/lib/python3.13/site-packages/rpmfluff/__init__.py", line 34, in <module>
    import rpm
ModuleNotFoundError: No module named 'rpm'
Traceback (most recent call last):
  File "/opt/kstest/kickstart-tests/scripts/httpd.py", line 52, in <module>
    os.chdir(sys.argv[1])
    ~~~~~~~~^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/kstest-repo-addrepo.2024_11_26-00_22_38.layjd04a/addon'
stdout:
/opt/kstest/kickstart-tests/repo-addrepo.ks

```

**Comment by rvykydal** [comment]
So it seems the problem happens only on one of our runners: [github-kstest-30-f39-20240408](https://rhos-d.infra.prod.upshift.rdu2.redhat.com/dashboard/project/instances/8ba3661e-1ec4-490f-bec7-99847f474426/)

**Comment by rvykydal** [comment]
Confirmed,  cause is the container newly based on f41

**Comment by rvykydal** [comment]
PR with base image update: https://github.com/rhinstaller/kickstart-tests/pull/1344

**Comment by rvykydal** [comment]
The /test-os-variants on https://github.com/rhinstaller/kickstart-tests/pull/1345 which triggers container rebuild shows that the issue should be gone.
