### ISSUE TITLE
packages-multilib failing on daily-iso with "conflicts between attempted installs of systemd-250~rc3-1.fc36.i686 and systemd-250~rc3-1.fc36.x86_64" 

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#641]
The packages-multilib test fails on daily-iso scenario with:
```
03:04:38,967 ERR anaconda:anaconda: modules.payloads.payload.dnf.dnf_manager: The transaction has ended abruptly: Transaction test error:#012  file /usr/share/dbus-1/interfaces/org.freedesktop.systemd1.Manager.xml conflicts between attempted installs of systemd-250~rc3-1.fc36.i686 and systemd-250~rc3-1.fc36.x86_64
03:04:39,023 DEBUG anaconda:anaconda: modules.payloads.payload.dnf.dnf_manager: The transaction has ended.
03:04:39,030 INFO anaconda:dnf: The downloaded packages were saved in cache until the next successful transaction.
03:04:39,031 INFO anaconda:dnf: You can remove cached packages by executing 'dnf clean packages'.
03:04:39,279 DEBUG anaconda:anaconda: modules.payloads.payload.dnf.dnf_manager: The transaction process exited with 0.
03:04:39,282 INFO anaconda:anaconda: threading: Thread Failed: AnaInstallThread (139959470114368)
03:04:39,283 DEBUG anaconda:anaconda: exception: running handleException
03:04:39,307 CRIT anaconda:anaconda: exception: Traceback (most recent call last):#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/threading.py", line 275, in run#012    threading.Thread.run(self)#012#012  File "/usr/lib64/python3.10/threading.py", line 946, in run#012    self._target(*self._args, **self._kwargs)#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation.py", line 424, in run_installation#012    queue.start()#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 496, in start#012    self.run_task()#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 458, in run_task#012    self._task(*self._task_args, **self._task_kwargs)#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/payload/dnf/payload.py", line 569, in install#012    task.run()#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/payloads/payload/dnf/installation.py", line 243, in run#012    self._dnf_manager.install_packages(self.report_progress)#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/payloads/payload/dnf/dnf_manager.py", line 666, in install_packages#012    process_transaction_progress(queue, callback)#012#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/payloads/payload/dnf/transaction_progress.py", line 57, in process_transaction_progress#012    raise RuntimeError("The transaction process has ended abruptly: " + msg)#012#012RuntimeError: The transaction process has ended abruptly: Transaction test error:#012  file /usr/share/dbus-1/interfaces/org.freedesktop.systemd1.Manager.xml conflicts between attempted installs of systemd-250~rc3-1.fc36.i686 and systemd-250~rc3-1.fc36.x86_64#012Traceback (most recent call last):#012  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/payloads/payload/dnf/dnf_manager.py", line 691, in _run_transaction#012    base.do_transaction(display)#012  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 958, in do_transaction#012    raise dnf.exceptions.Error(errstring)#012dnf.exceptions.Error: Transaction test error:#012  file /usr/share/dbus-1/interfaces/org.freedesktop.systemd1.Manager.xml conflicts between attempted installs of systemd-250~rc3-1.fc36.i686 and systemd-250~rc3-1.fc36.x86_64#012#012
03:04:39,384 DEBUG anaconda:anaconda: exception: Gtk running, queuing exception handler to the main loop
03:04:39,390 INFO anaconda:anaconda: threading: Thread Done: AnaInstallThread (139959470114368)
```

Started to appear on Daily run #413 (https://github.com/rhinstaller/kickstart-tests/actions/runs/1635654206)
Attaching test logs from the first failing run #413:
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/7801434/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/7801435/virt-install.log)

Logs from the last successful run #412:
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/7801440/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/7801442/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/642

**Comment by M4rtinK** [comment]
A quick bugzilla search does not show any relevant bugs for this - if the issue is still reproduceable in a few days, we might want to fill a bug for it.

**Comment by jkonecny12** [comment]
Daily ISO have a nightly builds on DNF so maybe that could be the problem?

**Comment by rvykydal** [comment]
Started to fail also on rhel9 scenario (Daily run Daily run #462 https://github.com/rhinstaller/kickstart-tests/actions/runs/1855691287):
```
pyanaconda.payload.errors.PayloadError: Payload error - DNF installation has ended up abruptly: Transaction test error:
  file /usr/share/dbus-1/interfaces/org.freedesktop.login1.Manager.xml conflicts between attempted installs of systemd-250-3.el9.i686 and systemd-250-3.el9.x86_64
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/8086707/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/8086708/virt-install.log)

**Comment by marusak** [comment]
Seems to work on rhel9, but still fails on fedora:
```
file /usr/lib/systemd/system/fwupd.service conflicts between attempted installs of fwupd-1.9.19-1.fc41.i686 and fwupd-1.9.19-1.fc41.x86_64
```

**Comment by marusak** [comment]
I can do
```
 %packages --multilib
-fwupd
 %end
```

But anaconda does not set up `multilib_policy=all` in `/etc/dnf/dnf.conf`.
