### ISSUE TITLE
harddrive-install-tree-relative test is unstable on daily-iso

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#694]
The test is resulting in a lot of flakes lately and even a failure (double-flake)

```
02:38:19,149 INFO anaconda:anaconda: lifecycle: Module initialized: CustomPartitioningSpoke
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.10/site-packages/dasbus/server/handler.py", line 455, in _method_callback
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    result = self._handle_call(
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.10/site-packages/dasbus/server/handler.py", line 265, in _handle_call
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return handler(*parameters, **additional_args)
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self.implementation.finish()
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/common/task/task.py", line 175, in finish
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threadMgr.raise_if_error(self._thread_name)
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/threading.py", line 166, in raise_if_error
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise exc_info[1]
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/threading.py", line 275, in run
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/threading.py", line 946, in run
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/payloads/base/initialization.py", line 60, in run
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    task.run_with_signals()
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/common/task/task.py", line 138, in run_with_signals
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/payloads/source/harddrive/initialization.py", line 91, in run
02:38:19,185 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise SourceSetupError(
02:38:19,190 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.payload.SourceSetupError: Nothing useful found for Hard drive ISO source at partition=/dev/vdb directory=repo/
02:38:19,193 ERR anaconda:anaconda: payload.manager: PayloadError: Nothing useful found for Hard drive ISO source at partition=/dev/vdb directory=repo/
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/8244670/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/8244672/virt-install.log

**Comment by poncovka** [comment]
From virt-install.log:

```
02:37:19,289 INFO anaconda:anaconda: main: Found a kickstart file: /run/install/ks.cfg
02:37:19,609 INFO anaconda:anaconda: kickstart.script: Running kickstart %%pre script(s)
02:37:19,615 INFO anaconda:anaconda: stdout: Running pre-installation scripts
02:37:19,618 INFO anaconda:program: Running... /bin/sh /tmp/ks-script-lh0200rh
02:37:20,263 INFO kernel:EXT4-fs (vdb): mounted filesystem with ordered data mode. Quota mode: none.
02:37:20,374 WARNING systemd-resolved:Using degraded feature set UDP+EDNS0 instead of TLS+EDNS0 for DNS server 10.0.2.3.
02:37:20,812 INFO kernel:loop3: detected capacity change from 0 to 45
02:37:20,827 WARNING kernel:isofs_fill_super: bread failed, dev=loop3, iso_blknum=16, block=32
02:37:21,356 INFO systemd:prep\x2dmount.mount: Deactivated successfully.
02:37:21,437 INFO anaconda:program: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
02:37:21,439 INFO anaconda:program: Dload  Upload   Total   Spent    Left  Speed
02:37:21,440 INFO anaconda:program: 
02:37:21,441 INFO anaconda:program: 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: ftp.tu-chemnitz.de
02:37:21,442 INFO anaconda:program: http://ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Server/x86_64/iso/

```

**Comment by rvykydal** [comment]
This week the issue made 5/6 daily-iso runs failures.
