### ISSUE TITLE
test flakes with INFO lvmdbusd:KeyError: 'vdo_operating_mode' appearing sporadically

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#724]
We have seen this flake on rhel9 scenario of Daily run #545
```
00:57:08,827 INFO lvmdbusd:2348:2348 - MThreadRunner: exception
00:57:08,827 INFO lvmdbusd: Traceback (most recent call last):
00:57:08,827 INFO lvmdbusd:  File "/usr/lib/python3.9/site-packages/lvmdbusd/utils.py", line 667, in _run
00:57:08,827 INFO lvmdbusd:    self.rc = self.f(*self.args)
00:57:08,827 INFO lvmdbusd:  File "/usr/lib/python3.9/site-packages/lvmdbusd/fetch.py", line 40, in _main_thread_load
00:57:08,827 INFO lvmdbusd:    (lv_changes, remove) = load_lvs(
00:57:08,827 INFO lvmdbusd:  File "/usr/lib/python3.9/site-packages/lvmdbusd/lv.py", line 143, in load_lvs
00:57:08,827 INFO lvmdbusd:    return common(
00:57:08,827 INFO lvmdbusd:  File "/usr/lib/python3.9/site-packages/lvmdbusd/loader.py", line 37, in common
00:57:08,827 INFO lvmdbusd:    objects = retrieve(search_keys, cache_refresh=False)
00:57:08,827 INFO lvmdbusd:  File "/usr/lib/python3.9/site-packages/lvmdbusd/lv.py", line 95, in lvs_state_retrieve
00:57:08,827 INFO lvmdbusd:    l['vdo_operating_mode'],
00:57:08,827 INFO lvmdbusd:KeyError: 'vdo_operating_mode'
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/8705945/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/8705946/virt-install.log)

**Comment by jkonecny12** [comment]
This seems like something we should file to the upstream?

**Comment by rvykydal** [comment]
Hit again on rhel9 in https://github.com/rhinstaller/kickstart-tests/actions/runs/2896452174

[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/9393890/virt-install.log)

**Comment by rvykydal** [comment]
> This seems like something we should file to the upstream?

https://bugzilla.redhat.com/show_bug.cgi?id=2120267

**Comment by rvykydal** [comment]
The https://bugzilla.redhat.com/show_bug.cgi?id=2120267 seems to be fixed.
