### ISSUE TITLE
raid-1-reqpart test fails on daily-iso, rhel-10: "boot loader install failed"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#777]
```
02:13:10,798 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running in chroot '/mnt/sysroot'... grub2-install --no-floppy /dev/vdb
02:13:13,379 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Installing for i386-pc platform.
02:13:13,380 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:grub2-install: warning: ../grub-core/partmap/gpt.c:194:this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
02:13:13,380 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:grub2-install: error: embedding is not possible, but this is required for RAID and LVM install.
02:13:13,380 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 1
```

```
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.storage.bootloader.installation:Bootloader installation has failed: boot loader install failed
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/bootloader/installation.py", line 139, in run
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:    install_boot_loader(storage=self._storage)
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/bootloader/utils.py", line 215, in install_boot_loader
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.bootloader.write()
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/bootloader/grub2.py", line 452, in write
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.install()
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/bootloader/grub2.py", line 441, in install
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise BootLoaderError("boot loader install failed")
02:13:25,478 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.storage.bootloader.base.BootLoaderError: boot loader install failed
02:13:25,480 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Failed: AnaTaskThread-InstallBootloaderTask-1 (140430648542912)
```

Explanation is in https://github.com/rhinstaller/kickstart-tests/pull/766#issuecomment-1216469810

**Comment by rvykydal** [comment]
I think we could
- disable the test on daily-iso
- open a BZ to fix the issue linked to ^
- create a non reqpart version of the test with workaround by @poncovka in https://github.com/rhinstaller/kickstart-tests/pull/766#issuecomment-1216469810
- maybe create non-gpt version of the test

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/778

**Comment by rvykydal** [comment]
PR to update the test and create a new one specifically for reqpart: https://github.com/rhinstaller/kickstart-tests/pull/1141
BZ ticket for reqpart with raid: https://bugzilla.redhat.com/show_bug.cgi?id=2277150

**Comment by rvykydal** [comment]
Fixed by moving to UEFI by default: https://github.com/rhinstaller/kickstart-tests/pull/1744
