### ISSUE TITLE
flakes on rhel8 scenario with "INFO rhsm-service:ERROR [rhsmlib.dbus.util:41] argument of type 'Undefined' is not iterable"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#780]
Started to appear in https://github.com/rhinstaller/kickstart-tests/actions/runs/2907762167

```
03:34:34,328 WARNING org.fedoraproject.Anaconda.Modules.Subscription:INFO:anaconda.threading:Running Thread: AnaTaskThread-RestoreRHSMDefaultsTask-1 (140034091730688)
03:34:34,332 WARNING org.fedoraproject.Anaconda.Modules.Subscription:DEBUG:anaconda.modules.subscription.installation:subscription: setting RHSM log level back to INFO
03:34:34,339 WARNING org.fedoraproject.Anaconda.Modules.Subscription:DEBUG:anaconda.modules.subscription.installation:subscription: making sure RHSM SSL certificate validation is enabled
03:34:34,436 INFO rhsm-service:DEBUG [rhsmlib.dbus.objects.config:122] Setting new configuration values: {'logging.default_log_level': 'INFO', 'server.insecure': '0'}
03:34:34,444 INFO rhsm-service:DEBUG [rhsmlib.dbus.server:231] Disabling directory watcher: CONFIG_WATCHER
03:34:34,444 INFO rhsm-service:DEBUG [rhsmlib.file_monitor:307] Temporary disabled watcher: /etc/rhsm/rhsm.conf for 5 seconds
03:34:34,495 INFO rhsm-service:DEBUG [rhsmlib.file_monitor:186] Thread Thread-FileSystemWatcher: Some event occurred: /etc/rhsm (/etc/rhsm/tmpxw7u_b2e)
03:34:34,499 INFO rhsm-service:DEBUG [rhsmlib.dbus.server:247] Enabling directory watcher: CONFIG_WATCHER
03:34:34,504 INFO rhsm-service:DEBUG [rhsmlib.file_monitor:192] Directory watcher: /etc/rhsm/rhsm.conf temporary disabled. Ignoring event.
03:34:34,513 INFO rhsm-service:WARNING [rhsm.logutil:170] logging already initialized
03:34:34,527 INFO rhsm-service:DEBUG [rhsmlib.file_monitor:186] Thread Thread-FileSystemWatcher: Some event occurred: /etc/rhsm (/etc/rhsm/rhsm.conf)
03:34:34,693 INFO rhsm-service:ERROR [rhsmlib.dbus.util:41] argument of type 'Undefined' is not iterable
03:34:34,693 INFO rhsm-service:Traceback (most recent call last):
03:34:34,693 INFO rhsm-service:  File "/usr/lib64/python3.6/site-packages/rhsmlib/dbus/util.py", line 38, in dbus_handle_exceptions
03:34:34,693 INFO rhsm-service:    ret = func(*args, **kwargs)
03:34:34,693 INFO rhsm-service:  File "/usr/lib64/python3.6/site-packages/rhsmlib/dbus/objects/config.py", line 151, in SetAll
03:34:34,693 INFO rhsm-service:    rhsm.logutil.init_logger(parser)
03:34:34,693 INFO rhsm-service:  File "/usr/lib64/python3.6/site-packages/rhsm/logutil.py", line 213, in init_logger
03:34:34,693 INFO rhsm-service:    for logger_name, logging_level in config.items('logging'):
03:34:34,693 INFO rhsm-service:  File "/usr/lib64/python3.6/site-packages/rhsm/config.py", line 280, in items
03:34:34,693 INFO rhsm-service:    if self.get(section, key) and len(self.get(section, key).strip()) > 0:
03:34:34,693 INFO rhsm-service:  File "/usr/lib64/python3.6/site-packages/rhsm/config.py", line 168, in get
03:34:34,693 INFO rhsm-service:    return SafeConfigParser.get(self, section, prop)
03:34:34,693 INFO rhsm-service:  File "/usr/lib/python3.6/site-packages/iniparse/compat.py", line 222, in get
03:34:34,693 INFO rhsm-service:    value = RawConfigParser.get(self, section, option, vars)
03:34:34,693 INFO rhsm-service:  File "/usr/lib/python3.6/site-packages/iniparse/compat.py", line 122, in get
03:34:34,693 INFO rhsm-service:    if option in sec:
03:34:34,693 INFO rhsm-service:TypeError: argument of type 'Undefined' is not iterable
03:34:34,717 INFO rhsm-service:WARNING [rhsm.logutil:170] logging already initialized
03:34:34,755 WARNING org.fedoraproject.Anaconda.Modules.Subscription:INFO:anaconda.threading:Thread Failed: AnaTaskThread-RestoreRHSMDefaultsTask-1 (140034091730688)
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-RestoreRHSMDefaultsTask-1 has failed: Traceback (most recent call last):
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/threading.py", line 280, in run
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    threading.Thread.run(self)
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/threading.py", line 885, in run
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    self._target(*self._args, **self._kwargs)
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/modules/common/task/task.py", line 97, in _task_run_callback
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    self._set_result(self.run())
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/modules/subscription/installation.py", line 126, in run
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    self._rhsm_config_proxy.SetAll(config_dict, "")
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 447, in _call_method
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    **kwargs,
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    return self._handle_method_error(error)
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    raise exception from None
03:34:34,825 WARNING org.fedoraproject.Anaconda.Modules.Subscription:dasbus.error.DBusError: {"exception": "TypeError", "severity": "error", "message": "argument of type 'Undefined' is not iterable"}
03:34:34,839 WARNING org.fedoraproject.Anaconda.Modules.Subscription:INFO:anaconda.threading:Thread Done: AnaTaskThread-RestoreRHSMDefaultsTask-1 (140034091730688)
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:Traceback (most recent call last):
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/server/handler.py", line 421, in _method_callback
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    *unwrap_variant(parameters)
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/server/handler.py", line 234, in _handle_call
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    return handler(*parameters)
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    self.implementation.finish()
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/modules/common/task/task.py", line 161, in finish
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    threadMgr.raise_if_error(self._thread_name)
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/threading.py", line 171, in raise_if_error
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/threading.py", line 280, in run
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    threading.Thread.run(self)
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/threading.py", line 885, in run
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    self._target(*self._args, **self._kwargs)
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/modules/common/task/task.py", line 97, in _task_run_callback
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    self._set_result(self.run())
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib64/python3.6/site-packages/pyanaconda/modules/subscription/installation.py", line 126, in run
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    self._rhsm_config_proxy.SetAll(config_dict, "")
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 447, in _call_method
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    **kwargs,
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    return self._handle_method_error(error)
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:    raise exception from None
03:34:35,363 WARNING org.fedoraproject.Anaconda.Modules.Subscription:dasbus.error.DBusError: {"exception": "TypeError", "severity": "error", "message": "argument of type 'Undefined' is not iterable"}
03:34:35,431 INFO anaconda:anaconda: threading: Thread Failed: AnaInstallThread (140584963520256)
03:34:35,433 DEBUG anaconda:anaconda: exception: running handleException
03:34:35,479 CRIT anaconda:anaconda: exception: Traceback (most recent call last):#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/threading.py", line 280, in run#012    threading.Thread.run(self)#012#012  File "/usr/lib64/python3.6/threading.py", line 885, in run#012    self._target(*self._args, **self._kwargs)#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/installation.py", line 406, in run_installation#012    queue.start()#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/installation_tasks.py", line 311, in start#012    item.start()#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/installation_tasks.py", line 490, in start#012    self.run_task()#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/installation_tasks.py", line 521, in run_task#012    sync_run_task(self._task_proxy)#012#012  File "/usr/lib64/python3.6/site-packages/pyanaconda/modules/common/task/__init__.py", line 46, in sync_run_task#012    task_proxy.Finish()#012#012  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 447, in _call_method#012    **kwargs,#012#012  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply#012    return self._handle_method_error(error)#012#012  File "/usr/lib/python3.6/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error#012    raise exception from None#012#012dasbus.error.DBusError: {"exception": "TypeError", "severity": "error", "message": "argument of type 'Undefined' is not iterable"}
03:34:35,599 DEBUG anaconda:anaconda: exception: Gtk running, queuing exception handler to the main loop
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/9443737/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/9443739/virt-install.log)

**Comment by rvykydal** [comment]
Similar to https://github.com/rhinstaller/kickstart-tests/issues/779.
May be related to https://github.com/rhinstaller/kickstart-tests/issues/707

**Comment by rvykydal** [comment]
Seems to disappear with https://github.com/rhinstaller/kickstart-tests/issues/707, closing as well.
