### ISSUE TITLE
repo-addrepo-hd-tree failing on rhel9 with "PayloadError: 'DeviceFormat' object has no attribute 'mount'"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#790]
https://github.com/rhinstaller/kickstart-tests/actions/runs/3041270133
```
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.Storage.DeviceTree.Handler.MountDevice has failed with an exception:
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 418, in _method_callback
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 234, in _handle_call
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters)
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/devicetree/handler_interface.py", line 57, in MountDevice
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.mount_device(device_name, mount_point, options)
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/devicetree/handler.py", line 95, in mount_device
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:    device.format.mount(mountpoint=mount_point, options=options or None)
03:20:53,196 WARNING org.fedoraproject.Anaconda.Modules.Storage:AttributeError: 'DeviceFormat' object has no attribute 'mount'
03:20:53,202 ERR anaconda:anaconda: payload.manager: PayloadError: 'DeviceFormat' object has no attribute 'mount'
03:20:53,203 DEBUG anaconda:anaconda: payload.manager: Updating payload thread state: ERROR
```
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/9554272/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/791

**Comment by rvykydal** [comment]
> PR to disable the test: #791

Fixup: https://github.com/rhinstaller/kickstart-tests/pull/792

**Comment by jkonecny12** [comment]
Fixup was merged. Can close this?

**Comment by rvykydal** [comment]
> Fixup was merged. Can close this?

It was a fixup of disabling of the test, the issue is still here to be dealt with so the test can be re-enabled.
