### ISSUE TITLE
rhel8 flake: "lvmdbusd:KeyError: 'pv_uuid'"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#845]
Hit on 12-20-2022.

```
01:17:33,628 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running [41] lvm pvcreate /dev/vda2 --config= devices { filter=["a|/dev/vda2$|","r|.*|"] } log {level=7 file=/tmp/lvm.log syslog=0} -y ...
01:17:33,831 INFO dbus-daemon:[system] Activating via systemd: service name='com.redhat.lvmdbus1' unit='lvm2-lvmdbusd.service' requested by ':1.30' (uid=0 pid=2507 comm="lvm pvcreate /dev/vda2 --config= devices { filter=" label="system_u:system_r:kernel_t:s0")
01:17:33,844 INFO systemd:Starting LVM2 D-Bus service...
01:17:33,950 INFO systemd:Condition check resulted in /dev/block/252:2 being skipped.
01:17:33,956 INFO systemd:Created slice system-lvm2\x2dpvscan.slice.
01:17:33,960 INFO systemd:Starting LVM event activation on device 252:2...
01:17:34,058 INFO lvm:  pvscan[2511] PV /dev/vda2 not used.
01:17:34,070 INFO systemd:Started LVM event activation on device 252:2. 
01:17:34,502 INFO dbus-daemon:[system] Successfully activated service 'com.redhat.lvmdbus1'
01:17:34,503 INFO systemd:Started LVM2 D-Bus service.
01:17:34,889 INFO lvmdbusd:Traceback (most recent call last):
01:17:34,889 INFO lvmdbusd:  File "/usr/sbin/lvmdbusd", line 16, in <module>
01:17:34,889 INFO lvmdbusd:    sys.exit(main())
01:17:34,889 INFO lvmdbusd:  File "/usr/lib/python3.6/site-packages/lvmdbusd/main.py", line 169, in main
01:17:34,889 INFO lvmdbusd:    updater = StateUpdate()
01:17:34,889 INFO lvmdbusd:  File "/usr/lib/python3.6/site-packages/lvmdbusd/fetch.py", line 205, in __init__
01:17:34,889 INFO lvmdbusd:    load(refresh=False, emit_signal=False, need_main_thread=False)
01:17:34,889 INFO lvmdbusd:  File "/usr/lib/python3.6/site-packages/lvmdbusd/fetch.py", line 80, in load
01:17:34,889 INFO lvmdbusd:    cfg.db.refresh(log)
01:17:34,889 INFO lvmdbusd:  File "/usr/lib/python3.6/site-packages/lvmdbusd/lvmdb.py", line 417, in refresh
01:17:34,889 INFO lvmdbusd:    _pvs, _pvs_lookup, _pvs_in_vgs = self._parse_pvs(_raw_pvs)
01:17:34,889 INFO lvmdbusd:  File "/usr/lib/python3.6/site-packages/lvmdbusd/lvmdb.py", line 97, in _parse_pvs
01:17:34,889 INFO lvmdbusd:    c_pvs, p['pv_uuid'], p,
01:17:34,889 INFO lvmdbusd:KeyError: 'pv_uuid'
01:17:34,926 INFO systemd:lvm2-lvmdbusd.service: Succeeded.
01:17:34,951 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:stdout[41]:   Physical volume "/dev/vda2" successfully created.
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/10335160/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10335158/virt-install.log)

**Comment by rvykydal** [comment]
09/06/2023
