### ISSUE TITLE
snapshot-pre flake on daily-iso: "gi.overrides.BlockDev.LVMError: Failed to call the 'Snapshot' method on the '/com/redhat/lvmdbus1/Lv/1' object: Timeout was reached"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#869]
01/13/2023

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/10424377/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10424378/virt-install.log)

**Comment by VladimirSlavik** [comment]
The log is spammed with rsyslog errors:
```
05:09:40,465 ERR rsyslogd:imjournal: fopen() failed for path: '/imjournal.state.tmp': Permission denied [v8.2210.0-2.fc38 try https://www.rsyslog.com/e/2013 ]
```

But then we also get:
```
05:09:40,731 DEBUG anaconda:anaconda: modules.payloads.payload.dnf.tree_info: Load treeinfo metadata for 'http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/$basearch/os/'.
05:09:40,808 NOTICE audit:AVC avc:  denied  { name_connect } for  pid=1849 comm="anaconda" dest=80 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=1
05:09:40,809 NOTICE kernel:audit: type=1400 audit(1673586580.806:654): avc:  denied  { name_connect } for  pid=1849 comm="anaconda" dest=80 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:http_port_t:s0 tclass=tcp_socket permissive=1
05:09:40,846 DEBUG anaconda:anaconda: modules.payloads.payload.dnf.tree_info: Failed to download '.treeinfo': 404 Client Error: Not Found for url: http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/$basearch/os//.treeinfo
05:09:40,867 DEBUG anaconda:anaconda: modules.payloads.payload.dnf.tree_info: Failed to download 'treeinfo': 404 Client Error: Not Found for url: http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/$basearch/os//treeinfo
05:09:40,870 DEBUG anaconda:packaging: No treeinfo metadata to use: No treeinfo metadata found (404).
(...)
05:09:51,009 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Failed: AnaTaskThread-SnapshotCreateTask-1 (140223056410304)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-SnapshotCreateTask-1 has failed: Traceback (most recent call last):
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 1200, in wrapped
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ret = orig_obj(*args, **kwargs)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:          ^^^^^^^^^^^^^^^^^^^^^^^^^
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 849, in lvm_thsnapshotcreate
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return _lvm_thsnapshotcreate(vg_name, origin_name, snapshot_name, pool_name, extra)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.repository.GLib.GError: g-io-error-quark: Failed to call the 'Snapshot' method on the '/com/redhat/lvmdbus1/Lv/1' object: Timeout was reached (24)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:During handling of the above exception, another exception occurred:
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 275, in run
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/threading.py", line 975, in run
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/snapshot/create.py", line 52, in run
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create_snapshots(self._storage, self._requests, self._when)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/snapshot/create.py", line 65, in _create_snapshots
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create_snapshot(storage, request)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/snapshot/create.py", line 83, in _create_snapshot
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    device.create()
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
05:09:51,021 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/storage.py", line 493, in create
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create()
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/lvm.py", line 2468, in decorated
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:    found, ret = self._try_specific_call(meth.__name__, *args, **kwargs)  # pylint: disable=no-member
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/lvm.py", line 2453, in _try_specific_call
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ret = getattr(cls, name)(self, *args, **kwargs)
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/lvm.py", line 1547, in _create
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:    blockdev.lvm.thsnapshotcreate(self.vg.name, self.origin.lvname, self._name,
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 1222, in wrapped
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise transform[1](msg)
05:09:51,024 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.overrides.BlockDev.LVMError: Failed to call the 'Snapshot' method on the '/com/redhat/lvmdbus1/Lv/1' object: Timeout was reached
05:09:51,027 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Done: AnaTaskThread-SnapshotCreateTask-1 (140223056410304)
```

**Comment by VladimirSlavik** [comment]
Good catch, thanks! Still does not answer the rest though.

**Comment by rvykydal** [comment]
Hit again on 10/26/2023

**Comment by rvykydal** [comment]
Closing, will be tracked in https://github.com/rhinstaller/kickstart-tests/issues/1311
