### ISSUE TITLE
raid-1 failing on rhel9: "INFO:program:grub2-install: error: ../grub-core/kern/disk.c:236:disk `mduuid/8aedefe40972d6a899b5bbe5ba49a04e' not found."

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#879]
```
00:14:57,500 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.modules.storage.bootloader.grub2:bootloader.py: mbr will be updated for grub2
00:14:57,500 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running in chroot '/mnt/sysroot'... grub2-install --no-floppy /dev/vda
00:15:01,185 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Installing for i386-pc platform.
00:15:01,185 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:grub2-install: error: ../grub-core/kern/disk.c:236:disk `mduuid/8aedefe40972d6a899b5bbe5ba49a04e' not found.
00:15:01,186 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 1
00:15:01,188 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.modules.storage.bootloader.grub2:bootloader.py: used boot args: crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M resume=UUID=9d2c9784-8a87-4e9c-bb73-efd59214e3b7 rd.md.uuid=60a209e9:bdef60e6:1c5132a9:c90113aa rd.md.uuid=8aedefe4:0972d6a8:99b5bbe5:ba49a04e rd.md.uuid=93567ce7:76a0e53f:ad5beb5e:ae9f786f
00:15:01,189 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running in chroot '/mnt/sysroot'... grub2-set-default 3484439642bb47b89406142d62136817-5.14.0-244.el9.x86_64
00:15:01,283 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 0
00:15:01,284 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running in chroot '/mnt/sysroot'... grub2-editenv - set menu_auto_hide=1 boot_success=1
00:15:01,303 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 0
00:15:01,304 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running in chroot '/mnt/sysroot'... grub2-mkconfig -o /boot/grub2/grub.cfg
00:15:03,244 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Generating grub configuration file ...
00:15:03,245 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:/usr/sbin/grub2-probe: error: ../grub-core/kern/disk.c:236:disk `mduuid/8aedefe40972d6a899b5bbe5ba49a04e' not found.
00:15:03,245 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 1
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.storage.bootloader.installation:Bootloader installation has failed: failed to write boot loader configuration
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/bootloader/grub2.py", line 442, in write
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.install()
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/bootloader/grub2.py", line 431, in install
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise BootLoaderError("boot loader install failed")
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.storage.bootloader.base.BootLoaderError: boot loader install failed
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:During handling of the above exception, another exception occurred:
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/bootloader/installation.py", line 139, in run
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:    install_boot_loader(storage=self._storage)
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/bootloader/utils.py", line 216, in install_boot_loader
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.bootloader.write()
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/bootloader/grub2.py", line 446, in write
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.write_config()
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/bootloader/grub2.py", line 363, in write_config
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise BootLoaderError("failed to write boot loader configuration")
00:15:03,264 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.storage.bootloader.base.BootLoaderError: failed to write boot loader configuration
00:15:03,265 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Failed: AnaTaskThread-InstallBootloaderTask-1 (140553762625088)
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-InstallBootloaderTask-1 has failed: Traceback (most recent call last):
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/threading.py", line 275, in run
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/threading.py", line 917, in run
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/bootloader/installation.py", line 142, in run
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise BootloaderInstallationError(str(e)) from None
00:15:03,271 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.installation.BootloaderInstallationError: failed to write boot loader configuration
00:15:03,273 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Done: AnaTaskThread-InstallBootloaderTask-1 (140553762625088)
```
01-29-2023
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/10534509/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10534510/virt-install.log)

packages of the last working daily image:
[lorax-packages.log](https://github.com/rhinstaller/kickstart-tests/files/10534574/lorax-packages.log)
packages of the first failing daily image:
[lorax-packages.log](https://github.com/rhinstaller/kickstart-tests/files/10534575/lorax-packages.log)
diff:
```
[rvykydal@prnot4 ~/work/kstests/weekly_reports/49/new_raid-1]$ diff succ/lorax-packages.log fail/lorax-packages.log 
364c364
< krb5-libs-1.19.1-24.el9_1.x86_64
---
> krb5-libs-1.20.1-3.el9.x86_64
535c535
< grub2-common-2.06-53.el9.noarch
---
> grub2-common-2.06-55.el9.noarch
539c539
< grub2-tools-minimal-2.06-53.el9.x86_64
---
> grub2-tools-minimal-2.06-55.el9.x86_64
548,549c548,549
< selinux-policy-38.1.4-1.el9.noarch
< selinux-policy-targeted-38.1.4-1.el9.noarch
---
> selinux-policy-38.1.5-1.el9.noarch
> selinux-policy-targeted-38.1.5-1.el9.noarch
640c640
< grub2-tools-2.06-53.el9.x86_64
---
> grub2-tools-2.06-55.el9.x86_64
686c686
< anaconda-user-help-9.0.0-1.el9.noarch
---
> anaconda-user-help-9.2.1-1.el9.noarch
726,727c726,727
< grub2-tools-efi-2.06-53.el9.x86_64
< grub2-tools-extra-2.06-53.el9.x86_64
---
> grub2-tools-efi-2.06-55.el9.x86_64
> grub2-tools-extra-2.06-55.el9.x86_64
736c736
< grub2-efi-x64-cdboot-2.06-53.el9.x86_64
---
> grub2-efi-x64-cdboot-2.06-55.el9.x86_64
```

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/880

**Comment by rvykydal** [comment]
Bootloader folks have been notified about the issue.

**Comment by marta-lewandowska** [comment]
grub2-2.06-56 appears to fix this issue

# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINTS
vda     253:0    0   10G  0 disk  
├─vda1  253:1    0  500M  0 part  
│ └─md0   9:0    0  499M  0 raid1 /boot
├─vda2  253:2    0  3.9G  0 part  
│ └─md2   9:2    0  7.8G  0 raid0 /
└─vda3  253:3    0    1G  0 part  
  └─md1   9:1    0 1022M  0 raid1 [SWAP]
vdb     253:16   0   10G  0 disk  
├─vdb1  253:17   0  500M  0 part  
│ └─md0   9:0    0  499M  0 raid1 /boot
├─vdb2  253:18   0  3.9G  0 part  
│ └─md2   9:2    0  7.8G  0 raid0 /
└─vdb3  253:19   0    1G  0 part  
  └─md1   9:1    0 1022M  0 raid1 [SWAP]
vdc     253:32   0   10G  0 disk  
vdd     253:48   0   10G  0 disk  
vde     253:64   0   10G  0 disk  
vdf     253:80   0   10G  0 disk  

# rpm -qa grub2\*
grub2-common-2.06-56.el9.noarch
grub2-pc-modules-2.06-56.el9.noarch
grub2-tools-minimal-2.06-56.el9.x86_64
grub2-tools-2.06-56.el9.x86_64
grub2-pc-2.06-56.el9.x86_64

**Comment by marta-lewandowska** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2092475 is the bug we're working on, which is a consequence (or a dupe) of https://bugzilla.redhat.com/show_bug.cgi?id=2143420

**Comment by rvykydal** [comment]
I am going to re-enable the test for the dailies: https://github.com/rhinstaller/kickstart-tests/pull/881

**Comment by rvykydal** [comment]
The last daily raid-1 test passed on rhel9 scenario.
