### ISSUE TITLE
All daily-iso tests failing with "type object 'DMTech' has no attribute 'MAP'"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#882]
Started on Feb 2 (https://github.com/rhinstaller/kickstart-tests/actions/runs/4069627073)

Maybe related to this change in libblockdev ?:
https://github.com/storaged-project/libblockdev/commit/e65f2ae3141c4c3e6a0f52af10db6a0c05363085

```
23:46:41,530 WARNING org.fedoraproject.Anaconda.Boss:INFO:anaconda.threading:Thread Failed: AnaTaskThread-StartModulesTask-1 (139701621053120)
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-StartModulesTask-1 has failed: Traceback (most recent call last):
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 145, in _start_service_by_name_handler
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    returned = call()
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:               ^^^^^^
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 466, in <lambda>
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    lambda: self._get_method_reply(getter),
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    return self._handle_method_error(error)
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    raise exception from None
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:dasbus.error.DBusError: Process org.fedoraproject.Anaconda.Modules.Storage exited with status 1
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:The above exception was the direct cause of the following exception:
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:Traceback (most recent call last):
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 275, in run
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    threading.Thread.run(self)
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/threading.py", line 975, in run
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    self._target(*self._args, **self._kwargs)
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    self._task_run_callback()
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    self._set_result(self.run())
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:                     ^^^^^^^^^^
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 77, in run
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    self._process_callbacks(self._module_observers)
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 193, in _process_callbacks
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:    is_available = callback(observer)
23:46:41,532 WARNING org.fedoraproject.Anaconda.Boss:                   ^^^^^^^^^^^^^^^^^^
23:46:41,533 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 147, in _start_service_by_name_handler
23:46:41,533 WARNING org.fedoraproject.Anaconda.Boss:    raise UnavailableModuleError(
23:46:41,533 WARNING org.fedoraproject.Anaconda.Boss:pyanaconda.modules.common.errors.module.UnavailableModuleError: Service org.fedoraproject.Anaconda.Modules.Storage has failed to start: Process org.fedoraproject.Anaconda.Modules.Storage exited with status 1
23:46:41,533 WARNING org.fedoraproject.Anaconda.Boss:INFO:anaconda.threading:Thread Done: AnaTaskThread-StartModulesTask-1 (139701621053120)
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:Traceback (most recent call last):
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 145, in _start_service_by_name_handler
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    returned = call()
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:               ^^^^^^
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 466, in <lambda>
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    lambda: self._get_method_reply(getter),
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    return self._handle_method_error(error)
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    raise exception from None
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:dasbus.error.DBusError: Process org.fedoraproject.Anaconda.Modules.Storage exited with status 1
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:The above exception was the direct cause of the following exception:
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:Traceback (most recent call last):
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 455, in _method_callback
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    result = self._handle_call(
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:             ^^^^^^^^^^^^^^^^^^
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 265, in _handle_call
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    return handler(*parameters, **additional_args)
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    self.implementation.finish()
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 175, in finish
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    threadMgr.raise_if_error(self._thread_name)
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 166, in raise_if_error
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    raise exc_info[1]
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 275, in run
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    threading.Thread.run(self)
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/threading.py", line 975, in run
23:46:41,624 WARNING org.fedoraproject.Anaconda.Boss:    self._target(*self._args, **self._kwargs)
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:    self._task_run_callback()
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:    self._set_result(self.run())
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:                     ^^^^^^^^^^
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 77, in run
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:    self._process_callbacks(self._module_observers)
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 193, in _process_callbacks
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:    is_available = callback(observer)
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:                   ^^^^^^^^^^^^^^^^^^
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/boss/module_manager/start_modules.py", line 147, in _start_service_by_name_handler
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:    raise UnavailableModuleError(
23:46:41,625 WARNING org.fedoraproject.Anaconda.Boss:pyanaconda.modules.common.errors.module.UnavailableModuleError: Service org.fedoraproject.Anaconda.Modules.Storage has failed to start: Process org.fedoraproject.Anaconda.Modules.Storage exited with status 1
```

[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10567485/virt-install.log)

packages diff:
```
[rvykydal@prnot4 ~/work/kstests/daily/276]$ diff prev/lorax-packages.log repro_logs/lorax-packages.log 
61c61
< containers-common-1-83.fc38.noarch
---
> containers-common-1-84.fc38.noarch
67,68c67,68
< createrepo_c-0.20.1-20230131005951.13.gc169f24.fc38.x86_64
< createrepo_c-libs-0.20.1-20230131005951.13.gc169f24.fc38.x86_64
---
> createrepo_c-0.20.1-20230201010506.13.gc169f24.fc38.x86_64
> createrepo_c-libs-0.20.1-20230201010506.13.gc169f24.fc38.x86_64
96,99c96,97
< dmraid-1.0.0.rc16-55.fc38.x86_64
< dmraid-libs-1.0.0.rc16-55.fc38.x86_64
< dnf-4.14.0-20230131005953.24.g07dac539.fc38.noarch
< dnf-data-4.14.0-20230131005953.24.g07dac539.fc38.noarch
---
> dnf-4.14.0-20230201010508.24.g07dac539.fc38.noarch
> dnf-data-4.14.0-20230201010508.24.g07dac539.fc38.noarch
166,169c164,167
< glibc-2.36.9000-24.fc38.x86_64
< glibc-all-langpacks-2.36.9000-24.fc38.x86_64
< glibc-common-2.36.9000-24.fc38.x86_64
< glibc-gconv-extra-2.36.9000-24.fc38.x86_64
---
> glibc-2.36.9000-25.fc38.x86_64
> glibc-all-langpacks-2.36.9000-25.fc38.x86_64
> glibc-common-2.36.9000-25.fc38.x86_64
> glibc-gconv-extra-2.36.9000-25.fc38.x86_64
193,202c191,200
< grub2-common-2.06-78.fc38.noarch
< grub2-efi-ia32-2.06-78.fc38.x86_64
< grub2-efi-ia32-cdboot-2.06-78.fc38.x86_64
< grub2-efi-x64-2.06-78.fc38.x86_64
< grub2-efi-x64-cdboot-2.06-78.fc38.x86_64
< grub2-pc-modules-2.06-78.fc38.noarch
< grub2-tools-2.06-78.fc38.x86_64
< grub2-tools-efi-2.06-78.fc38.x86_64
< grub2-tools-extra-2.06-78.fc38.x86_64
< grub2-tools-minimal-2.06-78.fc38.x86_64
---
> grub2-common-2.06-79.fc38.noarch
> grub2-efi-ia32-2.06-79.fc38.x86_64
> grub2-efi-ia32-cdboot-2.06-79.fc38.x86_64
> grub2-efi-x64-2.06-79.fc38.x86_64
> grub2-efi-x64-cdboot-2.06-79.fc38.x86_64
> grub2-pc-modules-2.06-79.fc38.noarch
> grub2-tools-2.06-79.fc38.x86_64
> grub2-tools-efi-2.06-79.fc38.x86_64
> grub2-tools-extra-2.06-79.fc38.x86_64
> grub2-tools-minimal-2.06-79.fc38.x86_64
279,283c277,281
< kernel-6.2.0-0.rc6.44.fc38.x86_64
< kernel-core-6.2.0-0.rc6.44.fc38.x86_64
< kernel-modules-6.2.0-0.rc6.44.fc38.x86_64
< kernel-modules-core-6.2.0-0.rc6.44.fc38.x86_64
< kernel-modules-extra-6.2.0-0.rc6.44.fc38.x86_64
---
> kernel-6.2.0-0.rc6.20230131git22b8077d0fce.45.fc38.x86_64
> kernel-core-6.2.0-0.rc6.20230131git22b8077d0fce.45.fc38.x86_64
> kernel-modules-6.2.0-0.rc6.20230131git22b8077d0fce.45.fc38.x86_64
> kernel-modules-core-6.2.0-0.rc6.20230131git22b8077d0fce.45.fc38.x86_64
> kernel-modules-extra-6.2.0-0.rc6.20230131git22b8077d0fce.45.fc38.x86_64
338,353c336,351
< libblockdev-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-btrfs-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-crypto-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-dm-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-fs-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-loop-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-lvm-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-lvm-dbus-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-mdraid-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-mpath-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-nvdimm-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-nvme-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-part-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-plugins-all-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-swap-2.99-41.20230117git2a84a1f0.fc38.x86_64
< libblockdev-utils-2.99-41.20230117git2a84a1f0.fc38.x86_64
---
> libblockdev-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-btrfs-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-crypto-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-dm-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-fs-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-loop-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-lvm-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-lvm-dbus-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-mdraid-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-mpath-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-nvdimm-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-nvme-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-part-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-plugins-all-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-swap-2.99-42.20230201gite65f2ae3.fc38.x86_64
> libblockdev-utils-2.99-42.20230201gite65f2ae3.fc38.x86_64
365c363
< libcomps-0.1.19-20230131005947.2.g85f148a.fc38.x86_64
---
> libcomps-0.1.19-20230201010501.2.g85f148a.fc38.x86_64
372c370
< libdnf-0.69.0-20230131005952.11.g943e3ac8.fc38.x86_64
---
> libdnf-0.69.0-20230201010507.11.g943e3ac8.fc38.x86_64
422c420
< libmodulemd-2.14.0-20230131005945.76.g4662d88.fc38.x86_64
---
> libmodulemd-2.14.0-20230201010459.76.g4662d88.fc38.x86_64
443c441
< librepo-1.15.1-20230131005946.0.g5f4de4a.fc38.x86_64
---
> librepo-1.15.1-20230201010501.0.g5f4de4a.fc38.x86_64
463c461
< libsolv-0.7.23-20230131005942.25.g8c7072d4.fc38.x86_64
---
> libsolv-0.7.23-20230201010456.26.gec0123c4.fc38.x86_64
479c477
< libtimezonemap-0.4.5.2-1.fc38.x86_64
---
> libtimezonemap-0.4.5.2-2.fc38.x86_64
613,614c611,612
< policycoreutils-3.5-0.rc2.1.fc38.1.x86_64
< policycoreutils-python-utils-3.5-0.rc2.1.fc38.1.noarch
---
> policycoreutils-3.5-0.rc2.2.fc38.x86_64
> policycoreutils-python-utils-3.5-0.rc2.2.fc38.noarch
631c629
< python3-blockdev-2.99-41.20230117git2a84a1f0.fc38.x86_64
---
> python3-blockdev-2.99-42.20230201gite65f2ae3.fc38.x86_64
640c638
< python3-dnf-4.14.0-20230131005953.24.g07dac539.fc38.noarch
---
> python3-dnf-4.14.0-20230201010508.24.g07dac539.fc38.noarch
646c644
< python3-hawkey-0.69.0-20230131005952.11.g943e3ac8.fc38.x86_64
---
> python3-hawkey-0.69.0-20230201010507.11.g943e3ac8.fc38.x86_64
650,651c648,649
< python3-libcomps-0.1.19-20230131005947.2.g85f148a.fc38.x86_64
< python3-libdnf-0.69.0-20230131005952.11.g943e3ac8.fc38.x86_64
---
> python3-libcomps-0.1.19-20230201010501.2.g85f148a.fc38.x86_64
> python3-libdnf-0.69.0-20230201010507.11.g943e3ac8.fc38.x86_64
662c660
< python3-policycoreutils-3.5-0.rc2.1.fc38.1.noarch
---
> python3-policycoreutils-3.5-0.rc2.2.fc38.noarch
708,710c706,708
< selinux-policy-38.5-2.fc38.noarch
< selinux-policy-targeted-38.5-2.fc38.noarch
< serd-0.30.12-3.fc38.x86_64
---
> selinux-policy-38.6-1.fc38.noarch
> selinux-policy-targeted-38.6-1.fc38.noarch
> serd-0.30.16-1.fc38.x86_64

```

**Comment by rvykydal** [comment]
> Maybe related to this change in libblockdev ?: [storaged-project/libblockdev@e65f2ae](https://github.com/storaged-project/libblockdev/commit/e65f2ae3141c4c3e6a0f52af10db6a0c05363085)

@vojtechtrefny what do you think ?

**Comment by vojtechtrefny** [comment]
Yes, that's our fault, https://github.com/storaged-project/libblockdev/pull/844 should fix this.

**Comment by rvykydal** [comment]
@vojtechtrefny: since 02/03/2023 all the daily-iso tests are failing with
```
23:26:56,283 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "<frozen runpy>", line 198, in _run_module_as_main
23:26:56,284 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "<frozen runpy>", line 88, in _run_code
23:26:56,284 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/__main__.py", line 24, in <module>
23:26:56,285 WARNING org.fedoraproject.Anaconda.Modules.Storage:    from pyanaconda.modules.storage.initialization import enable_installer_mode
23:26:56,285 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/initialization.py", line 19, in <module>
23:26:56,286 WARNING org.fedoraproject.Anaconda.Modules.Storage:    from blivet.devicelibs import crypto
23:26:56,286 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devicelibs/crypto.py", line 31, in <module>
23:26:56,286 WARNING org.fedoraproject.Anaconda.Modules.Storage:    from ..tasks import availability
23:26:56,287 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/tasks/availability.py", line 396, in <module>
23:26:56,287 WARNING org.fedoraproject.Anaconda.Modules.Storage:    technologies={blockdev.DMTech.RAID: BLOCKDEV_DM_ALL_MODES})
23:26:56,288 WARNING org.fedoraproject.Anaconda.Modules.Storage:                  ^^^^^^^^^^^^^^^^^^^^
23:26:56,288 WARNING org.fedoraproject.Anaconda.Modules.Storage:AttributeError: type object 'DMTech' has no attribute 'RAID'
```
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10662167/virt-install.log)

**Comment by vojtechtrefny** [comment]
This one should be fixed by this blivet PR: https://github.com/storaged-project/blivet/pull/1102

**Comment by rvykydal** [comment]
I can see it fixed in the latest daily run, thank you.
