### ISSUE TITLE
raid-ddf on rhel9 flake: "Failed to create storage layout: invalid device specification"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#884]
02-08-2023

```
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.storage.installation:Failed to create storage layout: invalid device specification
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/installation.py", line 86, in run
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._turn_on_filesystems(
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/installation.py", line 169, in _turn_on_filesystems
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.turn_on_swap()
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/blivet/threads.py", line 53, in run_with_lock
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/devicetree/model.py", line 429, in turn_on_swap
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.fsset.turn_on_swap(root_path=conf.target.system_root)
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/devicetree/fsset.py", line 532, in turn_on_swap
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    device.format.setup()
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/blivet/threads.py", line 53, in run_with_lock
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/blivet/formats/__init__.py", line 607, in setup
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    if not self._pre_setup(**kwargs):
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/blivet/threads.py", line 53, in run_with_lock
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/blivet/formats/__init__.py", line 634, in _pre_setup
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise FormatSetupError("invalid device specification")
00:25:57,491 WARNING org.fedoraproject.Anaconda.Modules.Storage:blivet.errors.FormatSetupError: invalid device specification
00:25:57,511 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Failed: AnaTaskThread-CreateStorageLayoutTask-1 (140426698810944)
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-CreateStorageLayoutTask-1 has failed: Traceback (most recent call last):
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/threading.py", line 275, in run
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/threading.py", line 917, in run
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/installation.py", line 98, in run
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageInstallationError(str(e)) from None
00:25:57,515 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.installation.StorageInstallationError: invalid device specification
00:25:57,524 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Done: AnaTaskThread-CreateStorageLayoutTask-1 (140426698810944)
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 418, in _method_callback
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 234, in _handle_call
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters)
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.finish()
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 175, in finish
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threadMgr.raise_if_error(self._thread_name)
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/threading.py", line 166, in raise_if_error
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise exc_info[1]
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/threading.py", line 275, in run
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/threading.py", line 917, in run
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/storage/installation.py", line 98, in run
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageInstallationError(str(e)) from None
00:25:58,419 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.installation.StorageInstallationError: invalid device specification
```

[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10721063/virt-install.log)

**Comment by rvykydal** [comment]
Not hit anymore
