### ISSUE TITLE
bindtomac-onboot-bootopts-pre flake on rhel9: "org.fedoraproject.Anaconda.Modules.Users:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#885]
02-08-2023
```
02:47:57,165 WARNING org.fedoraproject.Anaconda.Modules.Users:Traceback (most recent call last):
02:47:57,166 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
02:47:57,173 WARNING org.fedoraproject.Anaconda.Modules.Users:    return _run_code(code, main_globals, None,
02:47:57,173 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
02:47:57,178 WARNING org.fedoraproject.Anaconda.Modules.Users:    exec(code, run_globals)
02:47:57,179 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/users/__main__.py", line 25, in <module>
02:47:57,179 WARNING org.fedoraproject.Anaconda.Modules.Users:    service.run()
02:47:57,210 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/base/base.py", line 90, in run
02:47:57,210 WARNING org.fedoraproject.Anaconda.Modules.Users:    self.publish()
02:47:57,211 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/users/users.py", line 70, in publish
02:47:57,211 WARNING org.fedoraproject.Anaconda.Modules.Users:    DBus.publish_object(USERS.object_path, UsersInterface(self))
02:47:57,213 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 287, in publish_object
02:47:57,218 WARNING org.fedoraproject.Anaconda.Modules.Users:    object_handler.connect_object()
02:47:57,218 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 324, in connect_object
02:47:57,219 WARNING org.fedoraproject.Anaconda.Modules.Users:    self._register_object()
02:47:57,219 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 339, in _register_object
02:47:57,219 WARNING org.fedoraproject.Anaconda.Modules.Users:    self._message_bus.connection,
02:47:57,272 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 169, in connection
02:47:57,274 WARNING org.fedoraproject.Anaconda.Modules.Users:    self._connection = self._get_connection()
02:47:57,275 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/core/dbus.py", line 46, in _get_connection
02:47:57,276 WARNING org.fedoraproject.Anaconda.Modules.Users:    return self._provider.get_addressed_bus_connection(bus_address)
02:47:57,276 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 76, in get_addressed_bus_connection
02:47:57,283 WARNING org.fedoraproject.Anaconda.Modules.Users:    return Gio.DBusConnection.new_for_address_sync(
02:47:57,286 WARNING org.fedoraproject.Anaconda.Modules.Users:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10721249/virt-install.log)
```

**Comment by rvykydal** [comment]
03-30-2023

[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11136204/virt-install.log)

**Comment by rvykydal** [comment]
Tracked in https://github.com/rhinstaller/kickstart-tests/issues/1388 now
