### ISSUE TITLE
default-systemd-target-vnc-graphical-provides fails on daily-iso with "pyanaconda.errors.ExitError: gnome-kiosk exited on signal 11"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#890]
02-18-2023 double-flake
```
00:35:09,164 CRIT anaconda:anaconda: exception: Traceback (most recent call last):#012#012  File "/usr/lib64/python3.11/site-packages/gi/_ossighelper.py", line 92, in signal_notify#012    def signal_notify(source, condition):#012    #012#012  File "/usr/lib64/python3.11/site-packages/pyanaconda/core/process_watchers.py", line 117, in _sigchld_handler#012    cls._raise_exit_error(exit_statuses)#012#012  File "/usr/lib64/python3.11/site-packages/pyanaconda/core/process_watchers.py", line 81, in _raise_exit_error#012    raise ExitError(", ".join(exn_message))#012#012pyanaconda.errors.ExitError: gnome-kiosk exited on signal 11
```

[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10782740/virt-install.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10782742/virt-install.log)

**Comment by rvykydal** [comment]
02-20-2023
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10782805/virt-install.log)

**Comment by rvykydal** [comment]
02-23-2023
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10837857/virt-install.log)

**Comment by rvykydal** [comment]
02-25-2023 - double flake

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/895
