### ISSUE TITLE
rpm-ostree failing on daily-iso: "PayloadInstallationError: Failed to pull from repository"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#894]
02-27-2023

```
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-PullRemoteAndDeleteTask-1 has failed: Traceback (most recent call last):
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 603, in run
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    repo.pull_with_options(self._data.remote,
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:gi.repository.GLib.GError: g-io-error-quark: While fetching https://kojipkgs.fedoraproject.org/compose/iot/repo/objects/7f/7be1317dca708e1bbf79155ff8572d62a00863dbbeecb2fd8865f8479e7638.filez: [28] Timeout was reached (0)
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:The above exception was the direct cause of the following exception:
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 275, in run
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/threading.py", line 975, in run
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 607, in run
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError("Failed to pull from repository: %s" % e) from e
00:23:04,941 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: Failed to pull from repository: g-io-error-quark: While fetching https://kojipkgs.fedoraproject.org/compose/iot/repo/objects/7f/7be1317dca708e1bbf79155ff8572d62a00863dbbeecb2fd8865f8479e7638.filez: [28] Timeout was reached (0)
00:23:04,943 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:anaconda.threading:Thread Done: AnaTaskThread-PullRemoteAndDeleteTask-1 (140172143621824)
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 603, in run
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    repo.pull_with_options(self._data.remote,
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:gi.repository.GLib.GError: g-io-error-quark: While fetching https://kojipkgs.fedoraproject.org/compose/iot/repo/objects/7f/7be1317dca708e1bbf79155ff8572d62a00863dbbeecb2fd8865f8479e7638.filez: [28] Timeout was reached (0)
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:The above exception was the direct cause of the following exception:
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:Traceback (most recent call last):
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 455, in _method_callback
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    result = self._handle_call(
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:             ^^^^^^^^^^^^^^^^^^
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 265, in _handle_call
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    return handler(*parameters, **additional_args)
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self.implementation.finish()
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 175, in finish
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threadMgr.raise_if_error(self._thread_name)
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 166, in raise_if_error
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise exc_info[1]
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 275, in run
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    threading.Thread.run(self)
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/threading.py", line 975, in run
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._target(*self._args, **self._kwargs)
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._task_run_callback()
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    self._set_result(self.run())
00:23:05,019 WARNING org.fedoraproject.Anaconda.Modules.Payloads:                     ^^^^^^^^^^
00:23:05,020 WARNING org.fedoraproject.Anaconda.Modules.Payloads:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/payloads/payload/rpm_ostree/installation.py", line 607, in run
00:23:05,020 WARNING org.fedoraproject.Anaconda.Modules.Payloads:    raise PayloadInstallationError("Failed to pull from repository: %s" % e) from e
00:23:05,020 WARNING org.fedoraproject.Anaconda.Modules.Payloads:pyanaconda.modules.common.errors.installation.PayloadInstallationError: Failed to pull from repository: g-io-error-quark: While fetching https://kojipkgs.fedoraproject.org/compose/iot/repo/objects/7f/7be1317dca708e1bbf79155ff8572d62a00863dbbeecb2fd8865f8479e7638.filez: [28] Timeout was reached (0)
00:23:05,895 NOTICE audit:AVC avc:  denied  { execmem } for  pid=2088 comm="gnome-kiosk" scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=process permissive=1
```

**Comment by rvykydal** [comment]
03-05-2023 - a flake
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10896218/virt-install.log)

**Comment by rvykydal** [comment]
03-15-2023 - a flake
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11015624/virt-install.log)
