### ISSUE TITLE
snapshot-pre flake on daily-iso: "Anaconda.Modules.Storage:blivet.errors.FSError: device /dev/mapper/testvg-snap--test does not exist"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#906]
03-17-2023
```
23:34:03,074 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Done: AnaTaskThread-SnapshotCreateTask-1 (140451183064768)
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 455, in _method_callback
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:             ^^^^^^^^^^^^^^^^^^
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 265, in _handle_call
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters, **additional_args)
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.finish()
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 175, in finish
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threadMgr.raise_if_error(self._thread_name)
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 166, in raise_if_error
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise exc_info[1]
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 275, in run
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/threading.py", line 975, in run
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/snapshot/create.py", line 52, in run
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create_snapshots(self._storage, self._requests, self._when)
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/snapshot/create.py", line 65, in _create_snapshots
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create_snapshot(storage, request)
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/snapshot/create.py", line 87, in _create_snapshot
23:34:03,099 WARNING org.fedoraproject.Anaconda.Modules.Storage:    device.format.reset_uuid()
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/formats/fs.py", line 717, in reset_uuid
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.write_uuid()
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/formats/fs.py", line 1124, in write_uuid
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.mount(mountpoint=tmpdir, options="nouuid")
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/formats/fs.py", line 779, in mount
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return self.setup(**kwargs)
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/formats/__init__.py", line 607, in setup
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    if not self._pre_setup(**kwargs):
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/formats/fs.py", line 551, in _pre_setup
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise FSError("device %s does not exist" % self.device)
23:34:03,101 WARNING org.fedoraproject.Anaconda.Modules.Storage:blivet.errors.FSError: device /dev/mapper/testvg-snap--test does not exist
23:34:03,176 DEBUG anaconda:anaconda: exception: running handleException
23:34:03,180 CRIT anaconda:anaconda: exception: Traceback (most recent call last):#012#012  File "/sbin/anaconda", line 570, in <module>#012    sync_run_task(snapshot_task_proxy)#012#012  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/__init__.py", line 46, in sync_run_task#012    task_proxy.Finish()#012#012  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 450, in _call_method#012    return self._get_method_reply(#012           ^^^^^^^^^^^^^^^^^^^^^^^#012#012  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply#012    return self._handle_method_error(error)#012           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^#012#012  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error#012    raise exception from None#012#012pyanaconda.modules.common.errors.general.AnacondaError: device /dev/mapper/testvg-snap--test does not exist
```

[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11015915/virt-install.log)

**Comment by rvykydal** [comment]
05-15-2023
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11479265/virt-install.log)

**Comment by rvykydal** [comment]
05-30-2023
