### ISSUE TITLE
ignoredisk-1 flake on daily-iso: "Anaconda.Modules.Storage:pyanaconda.modules.common.errors.configuration.StorageConfigurationError: No usable disks."

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#907]
03-19-2023
```
02:04:29,013 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Failed: AnaTaskThread-AutomaticPartitioningTask-1 (139760799319744)
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-AutomaticPartitioningTask-1 has failed: Traceback (most recent call last):
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/partitioning/base_partitioning.py", line 53, in run
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._run(self._storage)
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/partitioning/automatic/noninteractive_partitioning.py", line 41, in _run
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._clear_partitions(storage)
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/partitioning/automatic/noninteractive_partitioning.py", line 111, in _clear_partitions
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise NoDisksError(_("No usable disks."))
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:blivet.errors.NoDisksError: No usable disks.
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:The above exception was the direct cause of the following exception:
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/threading.py", line 275, in run
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/threading.py", line 975, in run
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 96, in _thread_run_callback
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 109, in _task_run_callback
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/partitioning/base_partitioning.py", line 61, in run
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._handle_storage_error(e, str(e))
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/partitioning/base_partitioning.py", line 83, in _handle_storage_error
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageConfigurationError(message) from exception
02:04:29,020 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.configuration.StorageConfigurationError: No usable disks.
02:04:29,023 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.threading:Thread Done: AnaTaskThread-AutomaticPartitioningTask-1 (139760799319744)
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/11015945/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11015944/virt-install.log)

**Comment by rvykydal** [comment]
perhaps also this:
08-13-2023
preexisting-btrfs
```
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-AutomaticPartitioningTask-1 (140224598091456)
01:42:54,513 INFO anaconda:anaconda: core.threads: Running Thread: AnaExecuteStorageThread (140124471928512)
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-AutomaticPartitioningTask-1 has failed: Traceback (most recent call last):
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/partitioning/base_partitioning.py", line 53, in run
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._run(self._storage)
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/partitioning/automatic/noninteractive_partitioning.py", line 41, in _run
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._clear_partitions(storage)
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/partitioning/automatic/noninteractive_partitioning.py", line 111, in _clear_partitions
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise NoDisksError(_("No usable disks."))
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:blivet.errors.NoDisksError: No usable disks.
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:The above exception was the direct cause of the following exception:
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/threads.py", line 280, in run
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/threading.py", line 989, in run
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback() 
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/partitioning/base_partitioning.py", line 61, in run
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._handle_storage_error(e, str(e))
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.12/site-packages/pyanaconda/modules/storage/partitioning/base_partitioning.py", line 83, in _handle_storage_error
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise StorageConfigurationError(message) from exception
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:pyanaconda.modules.common.errors.configuration.StorageConfigurationError: No usable disks.
01:42:54,513 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-AutomaticPartitioningTask-1 (140224598091456)
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/12332732/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/12332733/virt-install.log)

**Comment by rvykydal** [comment]
Same message:
03-22-2024
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14740754/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14740755/virt-install.log)

**Comment by rvykydal** [comment]
04-11-2024
04-13-2024
hit for `ui-text-interactive`
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14975739/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14975745/virt-install.log)

**Comment by rvykydal** [comment]
Still active.
