### ISSUE TITLE
rhel9 flake: "Anaconda.Modules.Security:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#908]
03-19-2023
```
02:21:27,841 WARNING org.fedoraproject.Anaconda.Boss:DEBUG:anaconda.modules.boss.module_manager.start_modules:org.fedoraproject.Anaconda.Addons.Kdump is available.
02:21:27,842 WARNING org.fedoraproject.Anaconda.Addons.Kdump:DEBUG:anaconda.modules.common.base.base:Start the loop.
02:21:51,638 EMERG kernel:watchdog: BUG: soft lockup - CPU#0 stuck for 24s! [kworker/u2:1:11]
02:21:51,640 WARNING kernel:Modules linked in: intel_rapl_msr intel_rapl_common isst_if_common nfit libnvdimm rapl i2c_i801 i2c_smbus pcspkr lpc_ich virtio_balloon joydev fuse zram ext4 mbcache jbd2 loop nls_utf8 isofs sr_mod cdrom sg virtio_gpu virtio_dma_buf drm_shmem_helper drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ahci libahci drm libata 8021q garp mrp stp llc virtio_net crct10dif_pclmul crc32_pclmul net_failover ghash_clmulni_intel virtio_console failover virtio_blk serio_raw rfkill sunrpc lrw dm_crypt dm_round_robin dm_multipath dm_snapshot dm_bufio dm_mirror dm_region_hash dm_log dm_zero dm_mod linear raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx raid6_pq libcrc32c crc32c_intel raid1 raid0 iscsi_ibft squashfs be2iscsi bnx2i cnic uio cxgb4i cxgb4 tls libcxgbi libcxgb qla4xxx iscsi_boot_sysfs iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi edd
02:21:51,645 WARNING kernel:CPU: 0 PID: 11 Comm: kworker/u2:1 Not tainted 5.14.0-284.2.1.el9_2.x86_64 #1
02:21:51,645 WARNING kernel:Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.1-2.fc36 04/01/2014
02:21:51,645 WARNING kernel:Workqueue: loop1 loop_rootcg_workfn [loop]
02:21:51,645 WARNING kernel:RIP: 0010:_copy_to_iter+0x48b/0x6d0
02:21:51,645 WARNING kernel:Code: e0 06 49 03 01 48 2b 05 73 c0 f6 00 48 c1 f8 06 48 c1 e0 0c 48 03 05 74 c0 f6 00 48 01 c8 83 fa 08 0f 82 6f ff ff ff 48 8b 0e <48> 89 08 89 d1 48 8b 7c 0e f8 48 89 7c 08 f8 48 8d 78 08 48 83 e7
02:21:51,645 WARNING kernel:RSP: 0000:ffffa6ab40063b40 EFLAGS: 00010212
02:21:51,645 WARNING kernel:RAX: ffff9682c8806000 RBX: 000000002048b000 RCX: fffb40bd8b48ffff
02:21:51,645 WARNING kernel:RDX: 0000000000001000 RSI: ffff9682a158e000 RDI: ffff9682a158e000
02:21:51,645 WARNING kernel:RBP: 0000000000000000 R08: 0000000000000000 R09: ffffa6ab40063e20
02:21:51,645 WARNING kernel:R10: 0000000000001000 R11: ffff9682a158e000 R12: 0000000000001000
02:21:51,645 WARNING kernel:R13: 0000000000001000 R14: 0000000000000000 R15: ffffa6ab40063e30
02:21:51,646 WARNING kernel:FS:  0000000000000000(0000) GS:ffff9682f7e00000(0000) knlGS:0000000000000000
02:21:51,646 WARNING kernel:CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
02:21:51,646 WARNING kernel:CR2: 00007f8b3d2b1650 CR3: 000000007b636002 CR4: 0000000000770ef0
02:21:51,646 WARNING kernel:DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
02:21:51,646 WARNING kernel:DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
02:21:51,646 WARNING kernel:PKRU: 55555554
02:21:51,646 WARNING kernel:Call Trace:
02:21:51,646 WARNING kernel: <TASK>
02:21:51,646 WARNING kernel: ? filemap_get_pages+0x94/0x340
02:21:51,646 WARNING kernel: copy_page_to_iter+0x26f/0x490
02:21:51,647 WARNING kernel: filemap_read+0x18a/0x320
02:21:51,647 WARNING kernel: ? avc_has_perm+0x8f/0x1b0
02:21:51,647 WARNING kernel: do_iter_readv_writev+0x16c/0x190
02:21:51,647 WARNING kernel: do_iter_read+0xe9/0x170
02:21:51,647 WARNING kernel: loop_process_work+0x487/0x5f0 [loop]
02:21:51,647 WARNING kernel: process_one_work+0x1e5/0x3c0
02:21:51,647 WARNING kernel: worker_thread+0x50/0x3b0
02:21:51,647 WARNING kernel: ? rescuer_thread+0x3a0/0x3a0
02:21:51,647 WARNING kernel: kthread+0xd6/0x100
02:21:51,647 WARNING kernel: ? kthread_complete_and_exit+0x20/0x20
02:21:51,647 WARNING kernel: ret_from_fork+0x1f/0x30
02:21:51,647 WARNING kernel: </TASK>
02:21:53,173 INFO systemd:systemd-hostnamed.service: Deactivated successfully.
02:21:53,595 WARNING org.fedoraproject.Anaconda.Modules.Security:Traceback (most recent call last):
02:21:53,597 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
02:21:53,597 WARNING org.fedoraproject.Anaconda.Modules.Security:    return _run_code(code, main_globals, None,
02:21:53,597 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
02:21:53,598 WARNING org.fedoraproject.Anaconda.Modules.Security:    exec(code, run_globals)
02:21:53,598 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/security/__main__.py", line 25, in <module>
02:21:53,598 WARNING org.fedoraproject.Anaconda.Modules.Security:    service.run()
02:21:53,598 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/base/base.py", line 90, in run
02:21:53,598 WARNING org.fedoraproject.Anaconda.Modules.Security:    self.publish()
02:21:53,598 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/security/security.py", line 66, in publish
02:21:53,599 WARNING org.fedoraproject.Anaconda.Modules.Security:    DBus.publish_object(SECURITY.object_path, SecurityInterface(self))
02:21:53,599 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 287, in publish_object
02:21:53,599 WARNING org.fedoraproject.Anaconda.Modules.Security:    object_handler.connect_object()
02:21:53,599 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 324, in connect_object
02:21:53,599 WARNING org.fedoraproject.Anaconda.Modules.Security:    self._register_object()
02:21:53,599 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 339, in _register_object
02:21:53,600 WARNING org.fedoraproject.Anaconda.Modules.Security:    self._message_bus.connection,
02:21:53,600 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 169, in connection
02:21:53,600 WARNING org.fedoraproject.Anaconda.Modules.Security:    self._connection = self._get_connection()
02:21:53,600 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib64/python3.9/site-packages/pyanaconda/core/dbus.py", line 46, in _get_connection
02:21:53,601 WARNING org.fedoraproject.Anaconda.Modules.Security:    return self._provider.get_addressed_bus_connection(bus_address)
02:21:53,601 WARNING org.fedoraproject.Anaconda.Modules.Security:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 76, in get_addressed_bus_connection
02:21:53,601 WARNING org.fedoraproject.Anaconda.Modules.Security:    return Gio.DBusConnection.new_for_address_sync(
02:21:53,601 WARNING org.fedoraproject.Anaconda.Modules.Security:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
```
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11015986/virt-install.log)

**Comment by rvykydal** [comment]
See also https://github.com/rhinstaller/kickstart-tests/issues/905

**Comment by rvykydal** [comment]
Also a week before: 03-11-2023
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11016018/virt-install.log)

**Comment by rvykydal** [comment]
04-26-2023
```
03:53:06,797 WARNING org.fedoraproject.Anaconda.Modules.Services:DEBUG:anaconda.modules.common:The configuration is loaded from: ['/run/anaconda/anaconda.conf']
03:53:12,013 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:Traceback (most recent call last):
03:53:12,014 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
03:53:12,015 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    return _run_code(code, main_globals, None,
03:53:12,016 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
03:53:12,016 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    exec(code, run_globals)
03:53:12,016 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/share/anaconda/addons/org_fedora_oscap/service/__main__.py", line 26, in <module>
03:53:12,016 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    service.run()
03:53:12,016 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/base/base.py", line 90, in run
03:53:12,016 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    self.publish()
03:53:12,017 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/share/anaconda/addons/org_fedora_oscap/service/oscap.py", line 105, in publish
03:53:12,017 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    DBus.publish_object(OSCAP.object_path, OSCAPInterface(self))
03:53:12,017 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 287, in publish_object
03:53:12,017 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    object_handler.connect_object()
03:53:12,018 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 324, in connect_object
03:53:12,018 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    self._register_object()
03:53:12,019 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 339, in _register_object
03:53:12,019 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    self._message_bus.connection,
03:53:12,020 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 169, in connection
03:53:12,020 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    self._connection = self._get_connection()
03:53:12,020 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib64/python3.9/site-packages/pyanaconda/core/dbus.py", line 46, in _get_connection
03:53:12,020 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    return self._provider.get_addressed_bus_connection(bus_address)
03:53:12,020 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 76, in get_addressed_bus_connection
03:53:12,020 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:    return Gio.DBusConnection.new_for_address_sync(
03:53:12,022 WARNING org.fedoraproject.Anaconda.Addons.OSCAP:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
```
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11372906/virt-install.log)

**Comment by rvykydal** [comment]
05-05-2023 Users module

**Comment by rvykydal** [comment]
Tracked in https://github.com/rhinstaller/kickstart-tests/issues/1388 now
