### ISSUE TITLE
daily-iso flake: "org.fedoraproject.Anaconda.Modules.Network:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#933]
04-10-2023
```
23:50:07,081 WARNING org.fedoraproject.Anaconda.Modules.Network:Traceback (most recent call last):
23:50:07,082 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "<frozen runpy>", line 198, in _run_module_as_main
23:50:07,082 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "<frozen runpy>", line 88, in _run_code
23:50:07,082 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/network/__main__.py", line 25, in <module>
23:50:07,083 WARNING org.fedoraproject.Anaconda.Modules.Network:    service.run()
23:50:07,083 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/network/network.py", line 102, in run
23:50:07,083 WARNING org.fedoraproject.Anaconda.Modules.Network:    super().run()
23:50:07,083 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/base/base.py", line 90, in run
23:50:07,084 WARNING org.fedoraproject.Anaconda.Modules.Network:    self.publish()
23:50:07,084 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/network/network.py", line 94, in publish
23:50:07,084 WARNING org.fedoraproject.Anaconda.Modules.Network:    self._firewall_module.publish()
23:50:07,085 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/network/firewall/firewall.py", line 61, in publish
23:50:07,086 WARNING org.fedoraproject.Anaconda.Modules.Network:    DBus.publish_object(FIREWALL.object_path, FirewallInterface(self))
23:50:07,086 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib/python3.11/site-packages/dasbus/connection.py", line 290, in publish_object
23:50:07,086 WARNING org.fedoraproject.Anaconda.Modules.Network:    object_handler.connect_object()
23:50:07,086 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 355, in connect_object
23:50:07,108 WARNING org.fedoraproject.Anaconda.Modules.Network:    self._register_object()
23:50:07,108 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 370, in _register_object
23:50:07,108 WARNING org.fedoraproject.Anaconda.Modules.Network:    self._message_bus.connection,
23:50:07,109 WARNING org.fedoraproject.Anaconda.Modules.Network:    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:50:07,109 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib/python3.11/site-packages/dasbus/connection.py", line 169, in connection
23:50:07,109 WARNING org.fedoraproject.Anaconda.Modules.Network:    self._connection = self._get_connection()
23:50:07,110 WARNING org.fedoraproject.Anaconda.Modules.Network:                       ^^^^^^^^^^^^^^^^^^^^^^
23:50:07,110 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib64/python3.11/site-packages/pyanaconda/core/dbus.py", line 46, in _get_connection
23:50:07,110 WARNING org.fedoraproject.Anaconda.Modules.Network:    return self._provider.get_addressed_bus_connection(bus_address)
23:50:07,110 WARNING org.fedoraproject.Anaconda.Modules.Network:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:50:07,110 WARNING org.fedoraproject.Anaconda.Modules.Network:  File "/usr/lib/python3.11/site-packages/dasbus/connection.py", line 76, in get_addressed_bus_connection
23:50:07,111 WARNING org.fedoraproject.Anaconda.Modules.Network:    return Gio.DBusConnection.new_for_address_sync(
23:50:07,111 WARNING org.fedoraproject.Anaconda.Modules.Network:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:50:07,111 WARNING org.fedoraproject.Anaconda.Modules.Network:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
```
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11248288/virt-install.log)

**Comment by rvykydal** [comment]
Tracked in https://github.com/rhinstaller/kickstart-tests/issues/1388 now
