### ISSUE TITLE
all daily-iso tests failing with "org.fedoraproject.Anaconda.Modules.Storage:AttributeError: type object 'MDTech' has no attribute 'MD_TECH_MDRAID'" 

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#938]
Started to appear on 04-24-2023
```
23:42:49,034 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
23:42:49,036 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "<frozen runpy>", line 198, in _run_module_as_main
23:42:49,036 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "<frozen runpy>", line 88, in _run_code
23:42:49,036 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/__main__.py", line 24, in <module>
23:42:49,037 WARNING org.fedoraproject.Anaconda.Modules.Storage:    from pyanaconda.modules.storage.initialization import enable_installer_mode
23:42:49,040 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/initialization.py", line 19, in <module>
23:42:49,040 WARNING org.fedoraproject.Anaconda.Modules.Storage:    from blivet.devicelibs import crypto
23:42:49,043 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devicelibs/crypto.py", line 31, in <module>
23:42:49,044 WARNING org.fedoraproject.Anaconda.Modules.Storage:    from ..tasks import availability
23:42:49,044 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/tasks/availability.py", line 440, in <module>
23:42:49,044 WARNING org.fedoraproject.Anaconda.Modules.Storage:    technologies={blockdev.MDTech.MD_TECH_MDRAID: BLOCKDEV_MD_ALL_MODES})
23:42:49,044 WARNING org.fedoraproject.Anaconda.Modules.Storage:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23:42:49,044 WARNING org.fedoraproject.Anaconda.Modules.Storage:AttributeError: type object 'MDTech' has no attribute 'MD_TECH_MDRAID'
```
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11319607/virt-install.log)

**Comment by rvykydal** [comment]
@vojtechtrefny, perhaps related to some storage library update ?

**Comment by vojtechtrefny** [comment]
Looks like changing API in daily builds is not the best idea, who would have thought? Fix for libblockdev: https://github.com/storaged-project/libblockdev/pull/875

**Comment by rvykydal** [comment]
Thank you for the quick fix.
