### ISSUE TITLE
btrfs-2 flake on daily-iso: "naconda.Modules.Storage:gi.overrides.BlockDev.BtrfsError: Process reported exit code 1: ERROR: not a btrfs filesystem: /tmp/btrfs-tmp.168ffeqfjq3"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#954]
05-20-2023
```
03:45:19,491 INFO kernel:BTRFS: device label fedora-btrfs devid 1 transid 6 /dev/vda3 scanned by mount (3152)
03:45:19,513 INFO kernel:BTRFS info (device vda3): using crc32c (crc32c-intel) checksum algorithm
03:45:19,513 INFO kernel:BTRFS info (device vda3): using free space tree
03:45:19,537 ERR kernel:BTRFS error (device vda3): devid 2 uuid d36f0d41-3653-41e5-b766-98759e9e2c90 is missing
03:45:19,538 ERR kernel:BTRFS error (device vda3): failed to read the system array: -2
03:45:19,538 ERR kernel:BTRFS error (device vda3): open_ctree failed
03:45:19,549 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:stderr:
03:45:19,549 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b'mount: /tmp/btrfs-tmp.168ffeqfjq3: mount(2) system call failed: No such file or directory.'
03:45:19,550 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b'       dmesg(1) may have more information after failed mount system call.'
03:45:19,550 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 32
03:45:19,675 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Running... umount /tmp/btrfs-tmp.168ffeqfjq3
03:45:19,719 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:stderr:
03:45:19,720 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:b'umount: /tmp/btrfs-tmp.168ffeqfjq3: not mounted.'
03:45:19,720 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 32
03:45:19,731 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Failed: AnaTaskThread-CreateStorageLayoutTask-1 (139848149870272)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.common.task.task:Thread AnaTaskThread-CreateStorageLayoutTask-1 has failed: Traceback (most recent call last):
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 1227, in wrapped
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ret = orig_obj(*args, **kwargs)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:          ^^^^^^^^^^^^^^^^^^^^^^^^^
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 189, in btrfs_create_subvolume
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return _btrfs_create_subvolume(mountpoint, name, extra)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.repository.GLib.GError: g-bd-utils-exec-error-quark: Process reported exit code 1: ERROR: not a btrfs filesystem: /tmp/btrfs-tmp.168ffeqfjq3
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage: (0)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:During handling of the above exception, another exception occurred:
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/core/threads.py", line 280, in run
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/threading.py", line 975, in run
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/installation.py", line 87, in run
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._turn_on_filesystems(
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/installation.py", line 167, in _turn_on_filesystems
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.do_it(callbacks)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/blivet.py", line 114, in do_it
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.devicetree.actions.process(callbacks=callbacks, devices=self.devices)
03:45:19,829 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/actionlist.py", line 47, in wrapped_func
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return func(obj, *args, **kwargs)
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/actionlist.py", line 288, in process
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    action.execute(callbacks)
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/deviceaction.py", line 336, in execute
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.device.create()
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/storage.py", line 524, in create
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create()
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/btrfs.py", line 593, in _create
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    blockdev.btrfs.create_subvolume(mountpoint, self.name)
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 1249, in wrapped
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise transform[1](msg)
03:45:19,840 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.overrides.BlockDev.BtrfsError: Process reported exit code 1: ERROR: not a btrfs filesystem: /tmp/btrfs-tmp.168ffeqfjq3
03:45:19,868 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:anaconda.core.threads:Thread Done: AnaTaskThread-CreateStorageLayoutTask-1 (139848149870272)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Task.Finish has failed with an exception:
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 1227, in wrapped
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    ret = orig_obj(*args, **kwargs)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:          ^^^^^^^^^^^^^^^^^^^^^^^^^
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 189, in btrfs_create_subvolume
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return _btrfs_create_subvolume(mountpoint, name, extra)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.repository.GLib.GError: g-bd-utils-exec-error-quark: Process reported exit code 1: ERROR: not a btrfs filesystem: /tmp/btrfs-tmp.168ffeqfjq3
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage: (0)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:During handling of the above exception, another exception occurred:
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:Traceback (most recent call last):
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 455, in _method_callback
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    result = self._handle_call(
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:             ^^^^^^^^^^^^^^^^^^
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/dasbus/server/handler.py", line 265, in _handle_call
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return handler(*parameters, **additional_args)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task_interface.py", line 114, in Finish
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.implementation.finish()
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 173, in finish
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    thread_manager.raise_if_error(self._thread_name)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/core/threads.py", line 171, in raise_if_error
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise exc_info[1]
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/core/threads.py", line 280, in run
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    threading.Thread.run(self)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/threading.py", line 975, in run
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._target(*self._args, **self._kwargs)
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 94, in _thread_run_callback
03:45:19,987 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._task_run_callback()
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/common/task/task.py", line 107, in _task_run_callback
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._set_result(self.run())
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:                     ^^^^^^^^^^
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/installation.py", line 87, in run
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._turn_on_filesystems(
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/pyanaconda/modules/storage/installation.py", line 167, in _turn_on_filesystems
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    storage.do_it(callbacks)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/blivet.py", line 114, in do_it
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.devicetree.actions.process(callbacks=callbacks, devices=self.devices)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/actionlist.py", line 47, in wrapped_func
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return func(obj, *args, **kwargs)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^^^^^^^^^
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/actionlist.py", line 288, in process
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    action.execute(callbacks)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/deviceaction.py", line 336, in execute
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self.device.create()
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/storage.py", line 524, in create
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    self._create()
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/threads.py", line 53, in run_with_lock
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    return m(*args, **kwargs)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:           ^^^^^^^^^^^^^^^^^^
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib/python3.11/site-packages/blivet/devices/btrfs.py", line 593, in _create
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    blockdev.btrfs.create_subvolume(mountpoint, self.name)
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:  File "/usr/lib64/python3.11/site-packages/gi/overrides/BlockDev.py", line 1249, in wrapped
03:45:19,990 WARNING org.fedoraproject.Anaconda.Modules.Storage:    raise transform[1](msg)
03:45:19,991 WARNING org.fedoraproject.Anaconda.Modules.Storage:gi.overrides.BlockDev.BtrfsError: Process reported exit code 1: ERROR: not a btrfs filesystem: /tmp/btrfs-tmp.168ffeqfjq3
03:45:20,060 INFO anaconda:anaconda: core.threads: Thread Failed: AnaTaskThread-RunInstallationTask-1 (140505804457664)
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/11542435/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11542436/virt-install.log)

**Comment by rvykydal** [comment]
Not hit anymore.
