### ISSUE TITLE
A flake "EMERG kernel:watchdog: BUG: soft lockup - CPU#0 stuck for 26s! [instperf:2797"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#962]
06/02/2023
packages-instalangs-2
network-noipv4-pre
```
03:36:23,394 EMERG kernel:watchdog: BUG: soft lockup - CPU#0 stuck for 26s! [instperf:2797]
03:36:23,395 WARNING kernel:Modules linked in: intel_rapl_msr intel_rapl_common isst_if_common nfit libnvdimm rapl i2c_i801 i2c_smbus pcspkr virtio_balloon lpc_ich joydev fuse zram ext4 mbcache jbd2 loop nls_utf8 isofs sr_mod cdrom sg virtio_gpu virtio_dma_buf drm_shmem_helper drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops 8021q ahci garp mrp stp llc libahci drm libata crct10dif_pclmul crc32_pclmul virtio_net ghash_clmulni_intel net_failover virtio_blk virtio_console failover rfkill serio_raw sunrpc lrw dm_crypt dm_round_robin dm_multipath dm_snapshot dm_bufio dm_mirror dm_region_hash dm_log dm_zero dm_mod linear raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx raid6_pq libcrc32c crc32c_intel raid1 raid0 iscsi_ibft squashfs be2iscsi bnx2i cnic uio cxgb4i cxgb4 tls libcxgbi libcxgb qla4xxx iscsi_boot_sysfs iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi edd
03:36:23,400 WARNING kernel:CPU: 0 PID: 2797 Comm: instperf Not tainted 5.14.0-319.el9.x86_64 #1
03:36:23,400 WARNING kernel:Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.16.1-2.fc36 04/01/2014
03:36:23,401 WARNING kernel:RIP: 0010:copy_page+0x7/0x10
03:36:23,401 WARNING kernel:Code: 00 66 90 48 89 f8 48 89 d1 f3 a4 31 c0 c3 cc cc cc cc 48 89 c8 c3 cc cc cc cc cc cc cc cc cc cc cc cc cc 66 90 b9 00 02 00 00 <f3> 48 a5 c3 cc cc cc cc 90 48 83 ec 10 48 89 1c 24 4c 89 64 24 08
03:36:23,401 WARNING kernel:RSP: 0000:ffffb6508081bd20 EFLAGS: 00010286
03:36:23,401 WARNING kernel:RAX: 00007f6ded000000 RBX: ffffb6508081bde0 RCX: 0000000000000200
03:36:23,401 WARNING kernel:RDX: 0000000000000000 RSI: ffff97a3c8807000 RDI: ffff97a404800000
03:36:23,401 WARNING kernel:RBP: ffffd96181120000 R08: ffff97a437e377a8 R09: ffffd96181120000
03:36:23,401 WARNING kernel:R10: ffff97a437e377a8 R11: 0000000000000000 R12: ffff97a3f92cd9f8
03:36:23,401 WARNING kernel:R13: ffffd961802201c0 R14: ffff97a43a646400 R15: 0000000000000a55
03:36:23,401 WARNING kernel:FS:  00007f6ded5c5740(0000) GS:ffff97a437e00000(0000) knlGS:0000000000000000
03:36:23,401 WARNING kernel:CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
03:36:23,401 WARNING kernel:CR2: 00007f6ded000ae8 CR3: 000000007a526005 CR4: 0000000000770ef0
03:36:23,402 WARNING kernel:DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
03:36:23,402 WARNING kernel:DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
03:36:23,402 WARNING kernel:PKRU: 55555554
03:36:23,402 WARNING kernel:Call Trace:
03:36:23,402 WARNING kernel: <TASK>
03:36:23,402 WARNING kernel: wp_page_copy+0xd9/0x7e0
03:36:23,402 WARNING kernel: ? do_read_fault+0xde/0x160
03:36:23,403 WARNING kernel: __handle_mm_fault+0x585/0x650
03:36:23,403 WARNING kernel: handle_mm_fault+0xc5/0x2a0
03:36:23,404 WARNING kernel: do_user_addr_fault+0x1b4/0x6a0
03:36:23,404 WARNING kernel: exc_page_fault+0x62/0x150
03:36:23,404 WARNING kernel: asm_exc_page_fault+0x22/0x30
03:36:23,404 WARNING kernel:RIP: 0033:0x7f6decf185c8
03:36:23,404 WARNING kernel:Code: 00 64 48 2b 04 25 28 00 00 00 0f 85 f3 03 00 00 48 81 c4 d0 00 00 00 44 89 e8 5b 5d 41 5c 41 5d 41 5e c3 0f 1f 80 00 00 00 00 <48> 83 05 18 85 0e 00 04 48 8b 1d b9 19 0e 00 48 8b 83 40 10 00 00
03:36:23,404 WARNING kernel:RSP: 002b:00007fffffe8efd0 EFLAGS: 00010246
03:36:23,404 WARNING kernel:RAX: 0000000000000000 RBX: 0000000000000001 RCX: 00007f6decf18a10
03:36:23,404 WARNING kernel:RDX: 0000000000000000 RSI: 0000000000000018 RDI: 00007f6ded5c5a20
03:36:23,404 WARNING kernel:RBP: 0000000000000000 R08: 0000000000000000 R09: 00007f6ded55a0a0
03:36:23,404 WARNING kernel:R10: 00007f6ded5c5a10 R11: 0000000000000246 R12: 0000000000000000
03:36:23,404 WARNING kernel:R13: 0000000000000000 R14: 00007f6decd64040 R15: 0000000000000000
03:36:23,404 WARNING kernel: </TASK>
03:36:24,753 INFO systemd:systemd-hostnamed.service: Deactivated successfully.
03:36:24,850 WARNING org.fedoraproject.Anaconda.Modules.Users:Traceback (most recent call last):
03:36:24,852 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
03:36:24,858 WARNING org.fedoraproject.Anaconda.Modules.Users:    return _run_code(code, main_globals, None,
03:36:24,860 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
03:36:24,861 WARNING org.fedoraproject.Anaconda.Modules.Users:    exec(code, run_globals)
03:36:24,862 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/users/__main__.py", line 25, in <module>
03:36:24,862 WARNING org.fedoraproject.Anaconda.Modules.Users:    service.run()
03:36:24,862 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/common/base/base.py", line 90, in run
03:36:24,862 WARNING org.fedoraproject.Anaconda.Modules.Users:    self.publish()
03:36:24,862 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/modules/users/users.py", line 70, in publish
03:36:24,862 WARNING org.fedoraproject.Anaconda.Modules.Users:    DBus.publish_object(USERS.object_path, UsersInterface(self))
03:36:24,863 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 287, in publish_object
03:36:24,863 WARNING org.fedoraproject.Anaconda.Modules.Users:    object_handler.connect_object()
03:36:24,863 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 324, in connect_object
03:36:24,864 WARNING org.fedoraproject.Anaconda.Modules.Users:    self._register_object()
03:36:24,864 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/server/handler.py", line 339, in _register_object
03:36:24,864 WARNING org.fedoraproject.Anaconda.Modules.Users:    self._message_bus.connection,
03:36:24,864 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 169, in connection
03:36:24,865 WARNING org.fedoraproject.Anaconda.Modules.Users:    self._connection = self._get_connection()
03:36:24,865 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib64/python3.9/site-packages/pyanaconda/core/dbus.py", line 46, in _get_connection
03:36:24,865 WARNING org.fedoraproject.Anaconda.Modules.Users:    return self._provider.get_addressed_bus_connection(bus_address)
03:36:24,865 WARNING org.fedoraproject.Anaconda.Modules.Users:  File "/usr/lib/python3.9/site-packages/dasbus/connection.py", line 76, in get_addressed_bus_connection
03:36:24,866 WARNING org.fedoraproject.Anaconda.Modules.Users:    return Gio.DBusConnection.new_for_address_sync(
03:36:24,866 WARNING org.fedoraproject.Anaconda.Modules.Users:gi.repository.GLib.GError: g-io-error-quark: Timeout was reached (24)
03:36:26,211 WARNING org.fedoraproject.Anaconda.Modules.Localization:INFO:root:reading file=<gzip _io.BufferedReader name='/usr/lib/python3.9/site-packages/langtable/data/keyboards.xml.gz' 0x7f832fabc2e0>
03:36:26,279 WARNING org.fedoraproject.Anaconda.Modules.Localization:INFO:root:reading file=<gzip _io.BufferedReader name='/usr/lib/python3.9/site-packages/langtable/data/timezones.xml.gz' 0x7f832fabc310>
03:36:26,284 WARNING org.fedoraproject.Anaconda.Modules.Localization:INFO:root:reading file=<gzip _io.BufferedReader name='/usr/lib/python3.9/site-packages/langtable/data/timezoneidparts.xml.gz' 0x7f832fabc6d0>
```

[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/11677051/virt-install.log)

**Comment by rvykydal** [comment]
[virt-install.log](https://github.com/user-attachments/files/16408602/virt-install.log)
