### ISSUE TITLE
image-deployment-2 failing with "ERR anaconda:anaconda: ui.tui.hubs.summary: CmdlineError: The following mandatory spokes are not completed:#012Root password#012User creation"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#986]
Failing since 2023_07_20.
I think the test needs update or removal reflecting removing of `kickstart_modules` configuration setting https://github.com/rhinstaller/anaconda/pull/4764

```
02:04:18,766 DEBUG anaconda:simpleline: Starting main loop
02:04:18,778 DEBUG anaconda:simpleline: Processing screen ScreenData(SummaryHub,None,False)
02:04:18,843 DEBUG anaconda:simpleline: Input is required by ScreenData(SummaryHub,None,False) screen
02:04:18,862 ERR anaconda:anaconda: ui.tui.hubs.summary: CmdlineError: The following mandatory spokes are not completed:#012Root password#012User creation
02:04:18,862 DEBUG anaconda:simpleline: New signal ExceptionSignal enqueued with source ScreenScheduler
02:04:18,863 DEBUG anaconda:simpleline: Executing inner loop
02:04:18,863 DEBUG anaconda:simpleline: New signal ExceptionSignal enqueued with source ScreenScheduler
02:04:18,863 ERR anaconda:anaconda: ui.tui: #012======= Screen stack =======#012----------- TOP ------------#012ScreenData(SummaryHub,None,False)#012ScreenData(ProgressSpoke,None,False)#012============================
02:04:18,864 DEBUG anaconda:anaconda: exception: running handleException
02:04:18,865 CRIT anaconda:anaconda: exception: Traceback (most recent call last):#012#012  File "/usr/lib/python3.12/site-packages/simpleline/render/screen_scheduler.py", line 251, in _process_screen#012    top_screen.ui_screen.get_input_with_error_check(top_screen.args)#012#012  File "/usr/lib/python3.12/site-packages/simpleline/render/screen/__init__.py", line 296, in get_input_with_error_check#012    self._input_manager.get_input(args=args)#012#012  File "/usr/lib/python3.12/site-packages/simpleline/render/screen/input_manager.py", line 113, in get_input#012    prompt = self._ui_screen.prompt(args)#012             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^#012#012  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/tui/hubs/summary.py", line 124, in prompt#012    raise CmdlineError(errtxt)#012#012pyanaconda.errors.CmdlineError: The following mandatory spokes are not completed:#012Root password#012User creation
02:04:18,893 WARNING anaconda:anaconda: misc: /usr/lib/python3.12/site-packages/gi/overrides/__init__.py:108: DeprecationWarning: 'pkgutil.get_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead#012  override_loader = get_loader(override_package_name)
02:04:18,893 WARNING anaconda:anaconda: misc: /usr/lib64/python3.12/pkgutil.py:291: DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() instead#012  return find_loader(fullname)
02:04:18,974 NOTICE kernel:audit: type=1400 audit(1689818658.973:339): avc:  denied  { name_connect } for  pid=2672 comm="anaconda" dest=6001 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:xserver_port_t:s0 tclass=tcp_socket permissive=1
02:04:19,221 DEBUG anaconda:anaconda: exception: Gtk cannot be initialized
02:04:19,221 DEBUG anaconda:anaconda: exception: In the main thread, running exception handler
02:04:19,226 INFO anaconda:anaconda: core.util: Running kickstart %%onerror script(s)
02:04:19,227 INFO anaconda:anaconda: core.util: All kickstart %%onerror script(s) have been run
02:04:19,227 INFO anaconda:anaconda: kickstart.script: Running kickstart %%traceback script(s)
02:04:19,228 INFO anaconda:anaconda: kickstart.script: All kickstart %%traceback script(s) have been run
02:04:19,229 INFO anaconda:anaconda: core.util: Reporting the IPMI event: 10
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/12103553/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/12103556/virt-install.log)

**Comment by rvykydal** [comment]
@VladimirSlavik do you think we should update or remove the test ?

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/987

**Comment by rvykydal** [comment]
The test is now failing on rhel8 (perhaps missing the new configuration setting)

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/12142957/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/12142960/virt-install.log)

PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/991

Updating the test with condition for rhel8 may be a bit challenging. We do it in some tests in .ks.in (look at is_rhel8) file, but here the difference is in .sh file. Maybe, I'd create a special rhel8 version of the test.
