### ISSUE TITLE
daily-iso flakes: "pyanaconda.errors.ExitError: gnome-kiosk exited with status 1"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#997]
Since 08-11-2023

```
pyanaconda.errors.ExitError: gnome-kiosk exited with status 1
2023-08-11 00:58:21,280 INFO: RESULT:bond-vlan-pre:72f9a17f16f8:FAILED:Test failed on line: 00:58:15,660 CRIT anaconda:anaconda: exception: Traceback (most recent call last):

  File "/sbin/anaconda", line 575, in <module>
    anaconda.intf.setup(ksdata)

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/__init__.py", line 691, in setup
    self._actions = self.getActionClasses(self._list_hubs())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/__init__.py", line 701, in getActionClasses
    standalones = self._collectActionClasses(self.paths["spokes"], StandaloneSpoke)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/__init__.py", line 162, in _collectActionClasses
    collect(module_pattern,

  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/util.py", line 695, in collect
    __import__(module_pattern % mod_name)

  File "/usr/lib64/python3.12/site-packages/pyanaconda/ui/gui/spokes/custom_storage.py", line 45, in <module>
    from pyanaconda.modules.common.structures.device_factory import DeviceFactoryRequest, \

  File "<frozen importlib._bootstrap>", line 1266, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1237, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 841, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 990, in exec_module

  File "<frozen importlib._bootstrap_external>", line 1141, in get_code

  File "<frozen importlib._bootstrap_external>", line 1209, in _cache_bytecode

  File "<frozen importlib._bootstrap_external>", line 1234, in set_data

  File "<frozen importlib._bootstrap_external>", line 207, in _write_atomic

  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/process_watchers.py", line 117, in _sigchld_handler
    cls._raise_exit_error(exit_statuses)

  File "/usr/lib64/python3.12/site-packages/pyanaconda/core/process_watchers.py", line 81, in _raise_exit_error
    raise ExitError(", ".join(exn_message))

pyanaconda.errors.ExitError: gnome-kiosk exited with status 1
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/12332558/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/12332559/virt-install.log)

**Comment by rvykydal** [comment]
Packages diff:
[packages.diff.txt](https://github.com/rhinstaller/kickstart-tests/files/12332580/packages.diff.txt)

`gnome-kiosk` and `mutter` were updated. Anaconda had changes only in JS webui code.

```
11,18c11,18
< amd-gpu-firmware-20230625-151.fc39.noarch
< anaconda-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
< anaconda-core-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
< anaconda-dracut-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
< anaconda-gui-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
< anaconda-install-env-deps-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
< anaconda-install-img-deps-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
< anaconda-tui-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
---
> amd-gpu-firmware-20230804-152.fc40.noarch
> anaconda-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
> anaconda-core-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
> anaconda-dracut-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
> anaconda-gui-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
> anaconda-install-env-deps-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
> anaconda-install-img-deps-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
> anaconda-tui-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
20c20
< anaconda-widgets-39.29-1.20230808193131817083.master.55.g7e14044b70.fc39.x86_64
---
> anaconda-widgets-39.29-1.20230809134217498398.master.74.g5a187a22ae.fc39.x86_64
23c23
< atheros-firmware-20230625-151.fc39.noarch
---
> atheros-firmware-20230804-152.fc40.noarch
45c45
< brcmfmac-firmware-20230625-151.fc39.noarch
---
> brcmfmac-firmware-20230804-152.fc40.noarch
59c59
< chrony-4.4-0.4.pre2.fc39.x86_64
---
> chrony-4.4-1.fc40.x86_64
69,70c69,70
< createrepo_c-1.0.0-20230808005408.0.g0cc1392.fc39.x86_64
< createrepo_c-libs-1.0.0-20230808005408.0.g0cc1392.fc39.x86_64
---
> createrepo_c-1.0.0-20230809005510.0.g0cc1392.fc39.x86_64
> createrepo_c-libs-1.0.0-20230809005510.0.g0cc1392.fc39.x86_64
96c96
< device-mapper-persistent-data-1.0.5-1.fc39.x86_64
---
> device-mapper-persistent-data-1.0.6-1.fc40.x86_64
99,100c99,100
< dnf-4.16.2-20230808005411.1.g8e7ae4fc.fc39.noarch
< dnf-data-4.16.2-20230808005411.1.g8e7ae4fc.fc39.noarch
---
> dnf-4.16.2-20230810005614.1.g8e7ae4fc.fc39.noarch
> dnf-data-4.16.2-20230810005614.1.g8e7ae4fc.fc39.noarch
106c106
< drpm-0.5.2-20230808005404.0.g48c0fde.fc39.x86_64
---
> drpm-0.5.2-20230810005606.0.g48c0fde.fc39.x86_64
109c109
< dvb-firmware-20230625-151.fc39.noarch
---
> dvb-firmware-20230804-152.fc40.noarch
124c124
< fedora-gpg-keys-39-0.4.noarch
---
> fedora-gpg-keys-40-0.1.noarch
126,130c126,130
< fedora-release-39-0.21.noarch
< fedora-release-common-39-0.21.noarch
< fedora-release-identity-basic-39-0.21.noarch
< fedora-repos-39-0.4.noarch
< fedora-repos-rawhide-39-0.4.noarch
---
> fedora-release-40-0.2.noarch
> fedora-release-common-40-0.2.noarch
> fedora-release-identity-basic-40-0.2.noarch
> fedora-repos-40-0.1.noarch
> fedora-repos-rawhide-40-0.1.noarch
174c174
< gnome-kiosk-44.0-2.fc39.x86_64
---
> gnome-kiosk-44.0-3.fc40.x86_64
194c194
< grep-3.11-3.fc39.x86_64
---
> grep-3.11-4.fc40.x86_64
240c240
< intel-gpu-firmware-20230625-151.fc39.noarch
---
> intel-gpu-firmware-20230804-152.fc40.noarch
250,252c250,252
< iwlegacy-firmware-20230625-151.fc39.noarch
< iwlwifi-dvm-firmware-20230625-151.fc39.noarch
< iwlwifi-mvm-firmware-20230625-151.fc39.noarch
---
> iwlegacy-firmware-20230804-152.fc40.noarch
> iwlwifi-dvm-firmware-20230804-152.fc40.noarch
> iwlwifi-mvm-firmware-20230804-152.fc40.noarch
266,270c266,270
< kernel-6.5.0-0.rc5.36.fc39.x86_64
< kernel-core-6.5.0-0.rc5.36.fc39.x86_64
< kernel-modules-6.5.0-0.rc5.36.fc39.x86_64
< kernel-modules-core-6.5.0-0.rc5.36.fc39.x86_64
< kernel-modules-extra-6.5.0-0.rc5.36.fc39.x86_64
---
> kernel-6.5.0-0.rc5.20230809git13b937206866.38.fc40.x86_64
> kernel-core-6.5.0-0.rc5.20230809git13b937206866.38.fc40.x86_64
> kernel-modules-6.5.0-0.rc5.20230809git13b937206866.38.fc40.x86_64
> kernel-modules-core-6.5.0-0.rc5.20230809git13b937206866.38.fc40.x86_64
> kernel-modules-extra-6.5.0-0.rc5.20230809git13b937206866.38.fc40.x86_64
347c347
< libcloudproviders-0.3.1-8.fc39.x86_64
---
> libcloudproviders-0.3.2-1.fc40.x86_64
357c357
< libdnf-0.70.2-20230808005409.0.g998efa8f.fc39.x86_64
---
> libdnf-0.70.2-20230809005511.0.g998efa8f.fc39.x86_64
362a363
> libeis-1.0.0-2.fc39.x86_64
364,366c365
< libertas-sd8686-firmware-20230625-151.fc39.noarch
< libertas-sd8787-firmware-20230625-151.fc39.noarch
< libertas-usb8388-firmware-20230625-151.fc39.noarch
---
> libertas-firmware-20230804-152.fc40.noarch
406c405
< libmodulemd-2.15.0-20230808005403.0.gbfde7f2.fc39.x86_64
---
> libmodulemd-2.15.0-20230810005605.0.gbfde7f2.fc39.x86_64
427c426
< librepo-1.15.2-20230808005404.0.g1a0a5fd.fc39.x86_64
---
> librepo-1.15.2-20230810005607.0.g1a0a5fd.fc39.x86_64
447c446
< libsolv-0.7.24-20230808005400.11.g86717630.fc39.x86_64
---
> libsolv-0.7.24-20230810005602.11.g86717630.fc39.x86_64
467c466
< libudisks2-2.11.0-8.20230808gitb4924ca8.fc39.x86_64
---
> libudisks2-2.11.0-9.20230809git1bef32db.fc39.x86_64
469c468
< libunwind-1.7.0-0.2.rc2.fc39.x86_64
---
> libunwind-1.7.2-1.fc40.x86_64
500,501c499,500
< linux-firmware-20230625-151.fc39.noarch
< linux-firmware-whence-20230625-151.fc39.noarch
---
> linux-firmware-20230804-152.fc40.noarch
> linux-firmware-whence-20230804-152.fc40.noarch
537c536
< mt7xxx-firmware-20230625-151.fc39.noarch
---
> mt7xxx-firmware-20230804-152.fc40.noarch
541c540
< mutter-44.2-2.fc39.x86_64
---
> mutter-45~beta-6.fc40.x86_64
564c563
< nvidia-gpu-firmware-20230625-151.fc39.noarch
---
> nvidia-gpu-firmware-20230804-152.fc40.noarch
613c612
< python3-3.12.0~b4-3.fc39.x86_64
---
> python3-3.12.0~rc1-1.fc40.x86_64
623c622
< python3-dnf-4.16.2-20230808005411.1.g8e7ae4fc.fc39.noarch
---
> python3-dnf-4.16.2-20230810005614.1.g8e7ae4fc.fc39.noarch
628c627
< python3-hawkey-0.70.2-20230808005409.0.g998efa8f.fc39.x86_64
---
> python3-hawkey-0.70.2-20230809005511.0.g998efa8f.fc39.x86_64
633c632
< python3-libdnf-0.70.2-20230808005409.0.g998efa8f.fc39.x86_64
---
> python3-libdnf-0.70.2-20230809005511.0.g998efa8f.fc39.x86_64
635c634
< python3-libs-3.12.0~b4-3.fc39.x86_64
---
> python3-libs-3.12.0~rc1-1.fc40.x86_64
659a659
> qcom-firmware-20230804-152.fc40.noarch
666c666
< realtek-firmware-20230625-151.fc39.noarch
---
> realtek-firmware-20230804-152.fc40.noarch
713,717c713,717
< systemd-254-1.fc39.x86_64
< systemd-libs-254-1.fc39.x86_64
< systemd-pam-254-1.fc39.x86_64
< systemd-resolved-254-1.fc39.x86_64
< systemd-udev-254-1.fc39.x86_64
---
> systemd-254.1-2.fc40.x86_64
> systemd-libs-254.1-2.fc40.x86_64
> systemd-pam-254.1-2.fc40.x86_64
> systemd-resolved-254.1-2.fc40.x86_64
> systemd-udev-254.1-2.fc40.x86_64
726,727c726,727
< udisks2-2.11.0-8.20230808gitb4924ca8.fc39.x86_64
< udisks2-iscsi-2.11.0-8.20230808gitb4924ca8.fc39.x86_64
---
> udisks2-2.11.0-9.20230809git1bef32db.fc39.x86_64
> udisks2-iscsi-2.11.0-9.20230809git1bef32db.fc39.x86_64
753c753
< xfsprogs-6.3.0-3.fc39.x86_64
---
> xfsprogs-6.4.0-1.fc39.x86_64
775c775
< xrdb-1.2.1-6.fc39.x86_64
---
> xrdb-1.2.2-1.fc40.x86_64
```

**Comment by rvykydal** [comment]
Caused most probably by https://bugzilla.redhat.com/show_bug.cgi?id=2241632
